---
title: "Spiritual epidemiology WRANGLING (KW first pass)"
subtitle: "Last updated: 2019-04-17"
output:
  html_notebook:
    toc: yes
    toc_depth: 4
    toc_float: yes
always_allow_html: yes
---

This is Kara's first pass at wrangling the Spiritual Epidemiology data (with data from 2019-03-08). (Note: PDF printed portrait, 80% zoom, minimum margins.)

```{r global_options, include = F}
knitr::opts_chunk$set(fig.width = 4, fig.asp = 0.67,
                      include = F, echo = F)
```

```{r}
library(tidyverse)
library(langcog)
library(psych)
library(readxl)
library(cowplot)
library(lme4)
library(lmerTest)
library(kableExtra)
library(lubridate)

theme_set(theme_bw())
```

```{r}
d_raw <- read_xlsx("../Spiritual Epidemiology_Coded Data.xlsx", sheet = 3)
```

```{r}
var_key <- read_xlsx("../Spiritual Epidemiology_Coded Data.xlsx", sheet = 4) %>%
  rename(question = VARIABLE,
         question_renamed = `NEW VARIBALES`,
         question_text = QUESTION,
         response_options = `RESPONSE OPTIONS`,
         coding = CODING) %>%
  mutate(question_text = gsub("’", "'", question_text),
         question_text = gsub("—", " - ", question_text),
         question_text = gsub("“", "'", question_text),
         question_text = gsub("”", "'", question_text),
         question_text = gsub("\n", " ", question_text),
         question_text = gsub("\r", " ", question_text),
         question_text = gsub("  ", " ", question_text),
         question_text = gsub("  ", " ", question_text),
         question_text = gsub("  ", " ", question_text)) %>%
  mutate(order = 1:nrow(.)) %>%
  select(order, question, question_text) %>%
  arrange(order)
```

```{r}
# check for duplicates
duplicates <- d_raw %>%
  count(epi_ctry, epi_subj) %>%
  filter(n > 1)

d00 <- full_join(
  d_raw %>% filter((!epi_subj %in% duplicates$epi_subj)),
  d_raw %>% filter(epi_subj %in% duplicates$epi_subj & 
                     epi_batc == "First")) %>%
  mutate(epi_ctry = factor(epi_ctry,
                           levels = c("US", "Ghana", "Thailand",
                                      "China", "Vanuatu")))

d00 %>%
  count(epi_ctry, epi_subj) %>%
  filter(n > 1)

d00 %>% 
  distinct(epi_ctry, epi_subj) %>%
  count(epi_ctry)
```

```{r}
d0_epi_entry <- d00 %>% 
  select(epi_entr:epi_charc) #%>%
  # gather(question, response, -c(epi_batc, epi_ctry, epi_subj)) %>%
  # arrange(epi_ctry, epi_subj, epi_batc, question)
```

```{r}
d0_epi_1 <- d00 %>% 
  select(epi_batc:epi_subj, starts_with("epi_1_")) %>%
  mutate_at(vars(epi_1_01, epi_1_02, epi_1_03, epi_1_04, epi_1_05, epi_1_06,
                 epi_1_07, epi_1_08, epi_1_09, epi_1_10, epi_1_11, epi_1_12,
                 epi_1_13, epi_1_14, epi_1_15, epi_1_16),
            funs(num = as.numeric(.),
                 cat = recode_factor(.,
                                     "0" = "it does not happen",
                                     "0.5" = "it might happen",
                                     "1" = "it definitely happens"))) %>%
  select(-c(epi_1_01, epi_1_02, epi_1_03, epi_1_04, epi_1_05, epi_1_06,
            epi_1_07, epi_1_08, epi_1_09, epi_1_10, epi_1_11, epi_1_12,
            epi_1_13, epi_1_14, epi_1_15, epi_1_16)) %>%
  mutate_at(vars(epi_1_01a:epi_1_01c, epi_1_04a:epi_1_04c, 
                 epi_1_06a:epi_1_06c, epi_1_07a:epi_1_07c,
                 epi_1_11a:epi_1_11c, epi_1_14a:epi_1_14c),
            funs(num = as.numeric(.),
                 cat = recode_factor(.,
                                     "0" = "no",
                                     "1" = "a little",
                                     "2" = "a lot"))) %>%
  select(-c(epi_1_01a:epi_1_01c, epi_1_04a:epi_1_04c, 
            epi_1_06a:epi_1_06c, epi_1_07a:epi_1_07c,
            epi_1_11a:epi_1_11c, epi_1_14a:epi_1_14c)) %>%
  mutate_at(vars(epi_1_vut07a),
            funs(epi_1_vut07a_num = as.numeric(.),
                 epi_1_vut07a_cat = recode_factor(.,
                                                  "0" = "no",
                                                  "1" = "yes"))) %>%
  select(-c(epi_1_vut07a)) %>%
  mutate_at(vars(epi_1_chn16a:epi_1_chn16c),
            funs(num = as.numeric(.),
                 cat = recode_factor(.,
                                     "0" = "no",
                                     "0.5" = "maybe",
                                     "1" = "definitely"))) %>%
  select(-c(epi_1_chn16a:epi_1_chn16c)) # %>%
# gather(question, response, -c(epi_batc, epi_ctry, epi_subj)) %>%
# arrange(epi_ctry, epi_subj, epi_batc, question) %>%
# mutate(qtype1 = case_when(grepl("a_", question) |
#                             grepl("b_", question) |
#                             grepl("c_", question) ~ "follow-up",
#                           TRUE ~ "base"),
#        qtype2 = case_when(grepl("_num", question) ~ "numeric",
#                           grepl("_cat", question) ~ "categorical"))
```

```{r}
d0_epi_2 <- d00 %>% 
  select(epi_batc:epi_subj, contains("epi_2_")) %>%
  # response options: no (0) / maybe (0.5) / yes (1)
  mutate_at(vars(epi_2_01, epi_2_02, epi_2_03, epi_2_04, epi_2_05, epi_2_005a,
                 epi_2_06, epi_2_07, epi_2_08, epi_2_09, epi_2_10, epi_2_10c,
                 
                 epi_2_usa11, epi_2_gha11, epi_2_chn11, epi_2_vut11,
                 epi_2_usa12, epi_2_gha12, epi_2_chn12, epi_2_vut12, 
                 epi_2_usa13, epi_2_gha13, epi_2_chn13, epi_2_vut13, 
                 epi_2_usa14, epi_2_gha14, epi_2_chn14, epi_2_vut14, 
                 epi_2_usa15, epi_2_gha15, epi_2_chn15, epi_2_vut15,
                 
                 epi_2_16, epi_2_16b, epi_2_17, epi_2_18, epi_2_18a, 
                 epi_2_19, epi_2_vut19a, epi_2_20, epi_2_vut20a, epi_2_20a, 
                 epi_2_21, epi_2_22, epi_2_22a, epi_2_22b, epi_2_22c, 
                 epi_2_23, epi_2_23a, epi_2_23b, epi_2_23c,
                  
                 # USA
                 epi_2_usa11d, epi_2_usa12d, epi_2_usa13d, epi_2_usa14d,
                 epi_2_usa15d,
                 
                 # GHA
                 epi_2_gha11d, epi_2_gha12d, epi_2_gha13d, epi_2_gha14d,
                 epi_2_gha15d,
                 
                 # CHN
                 epi_2_chn11c, epi_2_chn12c, epi_2_chn13c, epi_2_chn14c,
                 epi_2_chn15c,
                 
                 # VUT
                 epi_2_vut11c, epi_2_vut12c, epi_2_vut13c, epi_2_vut14c,
                 epi_2_vut15c,
                 
                 # THL
                 epi_2_thl11, 
                 epi_2_thl12a, epi_2_thl12b, epi_2_thl12c, epi_2_thl12d,
                 epi_2_thl12e, epi_2_thl12f, epi_2_thl12g, epi_2_thl12h,
                 epi_2_thl12i, epi_2_thl12j, epi_2_thl12k,
                 `epi_2_thl#0`, epi_2_thl15, epi_2_thl24),
            funs(num = as.numeric(.),
                 cat = recode_factor(as.character(.),
                                     "0" = "no",
                                     "0.5" = "maybe",
                                     "1" = "yes"))) %>%
  select(-c(epi_2_01, epi_2_02, epi_2_03, epi_2_04, epi_2_05, epi_2_005a,
            epi_2_06, epi_2_07, epi_2_08, epi_2_09, epi_2_10, epi_2_10c,
            
            epi_2_usa11, epi_2_gha11, epi_2_chn11, epi_2_vut11,
            epi_2_usa12, epi_2_gha12, epi_2_chn12, epi_2_vut12, 
            epi_2_usa13, epi_2_gha13, epi_2_chn13, epi_2_vut13, 
            epi_2_usa14, epi_2_gha14, epi_2_chn14, epi_2_vut14, 
            epi_2_usa15, epi_2_gha15, epi_2_chn15, epi_2_vut15,
            
            epi_2_16, epi_2_16b, epi_2_17, epi_2_18, epi_2_18a, 
            epi_2_19, epi_2_vut19a, epi_2_20, epi_2_vut20a, epi_2_20a, 
            epi_2_21, epi_2_22, epi_2_22a, epi_2_22b, epi_2_22c, 
            epi_2_23, epi_2_23a, epi_2_23b, epi_2_23c,
            
            # USA
            epi_2_usa11d, epi_2_usa12d, epi_2_usa13d, epi_2_usa14d,
            epi_2_usa15d,
            
            # GHA
            epi_2_gha11d, epi_2_gha12d, epi_2_gha13d, epi_2_gha14d,
            epi_2_gha15d,
            
            # CHN
            epi_2_chn11c, epi_2_chn12c, epi_2_chn13c, epi_2_chn14c,
            epi_2_chn15c,
            
            # VUT
            epi_2_vut11c, epi_2_vut12c, epi_2_vut13c, epi_2_vut14c,
            epi_2_vut15c,
            
            # THL
            epi_2_thl11, 
            epi_2_thl12a, epi_2_thl12b, epi_2_thl12c, epi_2_thl12d,
            epi_2_thl12e, epi_2_thl12f, epi_2_thl12g, epi_2_thl12h,
            epi_2_thl12i, epi_2_thl12j, epi_2_thl12k,
            `epi_2_thl#0`, epi_2_thl15, epi_2_thl24)) %>%
  # response options: 0-15 min (1) / 15-30 min (2) / 30-60 min (3) / More than 1 hour (4)
  mutate_at(vars(epi_2_01a),
            funs(epi_2_01a_cat = factor(epi_2_01a,
                                        levels = c("0-15 min", "15-30 min",
                                                   "30-60 min", 
                                                   "More than 1 hour")),
                 epi_2_01a_num = as.numeric(epi_2_01a_cat))) %>%
  select(-c(epi_2_01a)) %>%
  # response options: no (0) / yes (1)
  mutate_at(vars(epi_2_03b:epi_2_03d, epi_2_06a:epi_2_06c, epi_2_08a, epi_2_09a,
                 
                 # USA
                 epi_2_usa11c_chk, epi_2_usa12c_chk, epi_2_usa13c_chk, 
                 epi_2_usa14c_chk, epi_2_usa15c_chk,
                 
                 # VUT
                 epi_2_vut11_a:epi_2_vut11_c, epi_2_vut15_a:epi_2_vut15_a),
            funs(num = as.numeric(.),
                 cat = recode_factor(as.character(.),
                                     "0" = "no",
                                     "1" = "yes"))) %>%
  select(-c(epi_2_03b:epi_2_03d, epi_2_06a:epi_2_06c, epi_2_08a, epi_2_09a, 
            
            # USA
            epi_2_usa11c_chk, epi_2_usa12c_chk, epi_2_usa13c_chk, 
            epi_2_usa14c_chk, epi_2_usa15c_chk,
            
            # VUT
            epi_2_vut11_a:epi_2_vut11_c, epi_2_vut15_a:epi_2_vut15_a)) %>%
  # response options: never (0) / once or twice (1) / at least once a year (2) / at least once a month (3) / at least once a week (4) / even more (5)
  mutate(epi_2_02a_num = case_when(!is.na(epi_2_02a_1) ~ 0,
                                   !is.na(epi_2_02a_2) ~ 1,
                                   !is.na(epi_2_02a_3) ~ 2,
                                   !is.na(epi_2_02a_4) ~ 3,
                                   !is.na(epi_2_02a_5) ~ 4,
                                   !is.na(epi_2_02a_6) ~ 5),
         epi_2_03e_num = case_when(!is.na(epi_2_03e_1) ~ 0,
                                   !is.na(epi_2_03e_2) ~ 1,
                                   !is.na(epi_2_03e_3) ~ 2,
                                   !is.na(epi_2_03e_4) ~ 3,
                                   !is.na(epi_2_03e_5) ~ 4,
                                   !is.na(epi_2_03e_6) ~ 5),
         epi_2_04a_num = case_when(!is.na(epi_2_04a_1) ~ 0,
                                   !is.na(epi_2_04a_2) ~ 1,
                                   !is.na(epi_2_04a_3) ~ 2,
                                   !is.na(epi_2_04a_4) ~ 3,
                                   !is.na(epi_2_04a_5) ~ 4,
                                   !is.na(epi_2_04a_6) ~ 5),
         epi_2_05a_num = case_when(!is.na(epi_2_05a_1) ~ 0,
                                   !is.na(epi_2_05a_2) ~ 1,
                                   !is.na(epi_2_05a_3) ~ 2,
                                   !is.na(epi_2_05a_4) ~ 3,
                                   !is.na(epi_2_05a_5) ~ 4,
                                   !is.na(epi_2_05a_6) ~ 5),
         epi_2_06d_num = case_when(!is.na(epi_2_06d_1) ~ 0,
                                   !is.na(epi_2_06d_2) ~ 1,
                                   !is.na(epi_2_06d_3) ~ 2,
                                   !is.na(epi_2_06d_4) ~ 3,
                                   !is.na(epi_2_06d_5) ~ 4,
                                   !is.na(epi_2_06d_6) ~ 5),
         epi_2_07a_num = case_when(!is.na(epi_2_07a_1) ~ 0,
                                   !is.na(epi_2_07a_2) ~ 1,
                                   !is.na(epi_2_07a_3) ~ 2,
                                   !is.na(epi_2_07a_4) ~ 3,
                                   !is.na(epi_2_07a_5) ~ 4,
                                   !is.na(epi_2_07a_6) ~ 5),
         epi_2_08b_num = case_when(!is.na(epi_2_08b_1) ~ 0,
                                   !is.na(epi_2_08b_2) ~ 1,
                                   !is.na(epi_2_08b_3) ~ 2,
                                   !is.na(epi_2_08b_4) ~ 3,
                                   !is.na(epi_2_08b_5) ~ 4,
                                   !is.na(epi_2_08b_6) ~ 5),
         epi_2_09b_num = case_when(!is.na(epi_2_09b_1) ~ 0,
                                   !is.na(epi_2_09b_2) ~ 1,
                                   !is.na(epi_2_09b_3) ~ 2,
                                   !is.na(epi_2_09b_4) ~ 3,
                                   !is.na(epi_2_09b_5) ~ 4,
                                   !is.na(epi_2_09b_6) ~ 5),
         epi_2_10b_num = case_when(!is.na(epi_2_10b_1) ~ 0,
                                   !is.na(epi_2_10b_2) ~ 1,
                                   !is.na(epi_2_10b_3) ~ 2,
                                   !is.na(epi_2_10b_4) ~ 3,
                                   !is.na(epi_2_10b_5) ~ 4,
                                   !is.na(epi_2_10b_6) ~ 5),
         
         # USA
         epi_2_usa11b_num = case_when(!is.na(epi_2_usa11b_1) ~ 0,
                                      !is.na(epi_2_usa11b_2) ~ 1,
                                      !is.na(epi_2_usa11b_3) ~ 2,
                                      !is.na(epi_2_usa11b_4) ~ 3,
                                      !is.na(epi_2_usa11b_5) ~ 4,
                                      !is.na(epi_2_usa11b_6) ~ 5),
         epi_2_usa11c_1_num = case_when(!is.na(epi_2_usa11c_1_1) ~ 0,
                                        !is.na(epi_2_usa11c_1_3) ~ 1,
                                        !is.na(epi_2_usa11c_1_5) ~ 2,
                                        !is.na(epi_2_usa11c_1_7) ~ 3,
                                        !is.na(epi_2_usa11c_1_9) ~ 4,
                                        !is.na(epi_2_usa11c_1_11) ~ 5),
         epi_2_usa11c_2_num = case_when(!is.na(epi_2_usa11c_2_1) ~ 0,
                                        !is.na(epi_2_usa11c_2_3) ~ 1,
                                        !is.na(epi_2_usa11c_2_5) ~ 2,
                                        !is.na(epi_2_usa11c_2_7) ~ 3,
                                        !is.na(epi_2_usa11c_2_9) ~ 4,
                                        !is.na(epi_2_usa11c_2_11) ~ 5),
         epi_2_usa11c_3_num = case_when(!is.na(epi_2_usa11c_3_1) ~ 0,
                                        !is.na(epi_2_usa11c_3_3) ~ 1,
                                        !is.na(epi_2_usa11c_3_5) ~ 2,
                                        !is.na(epi_2_usa11c_3_7) ~ 3,
                                        !is.na(epi_2_usa11c_3_9) ~ 4,
                                        !is.na(epi_2_usa11c_3_11) ~ 5),
         epi_2_usa11c_4_num = case_when(!is.na(epi_2_usa11c_4_1) ~ 0,
                                        !is.na(epi_2_usa11c_4_3) ~ 1,
                                        !is.na(epi_2_usa11c_4_5) ~ 2,
                                        !is.na(epi_2_usa11c_4_7) ~ 3,
                                        !is.na(epi_2_usa11c_4_9) ~ 4,
                                        !is.na(epi_2_usa11c_4_11) ~ 5),
         epi_2_usa11c_5_num = case_when(!is.na(epi_2_usa11c_5_1) ~ 0,
                                        !is.na(epi_2_usa11c_5_3) ~ 1,
                                        !is.na(epi_2_usa11c_5_5) ~ 2,
                                        !is.na(epi_2_usa11c_5_7) ~ 3,
                                        !is.na(epi_2_usa11c_5_9) ~ 4,
                                        !is.na(epi_2_usa11c_5_11) ~ 5),
         epi_2_usa11c_6_num = case_when(!is.na(epi_2_usa11c_6_1) ~ 0,
                                        !is.na(epi_2_usa11c_6_3) ~ 1,
                                        !is.na(epi_2_usa11c_6_5) ~ 2,
                                        !is.na(epi_2_usa11c_6_7) ~ 3,
                                        !is.na(epi_2_usa11c_6_9) ~ 4,
                                        !is.na(epi_2_usa11c_6_11) ~ 5),
         epi_2_usa11c_7_num = case_when(!is.na(epi_2_usa11c_7_1) ~ 0,
                                        !is.na(epi_2_usa11c_7_3) ~ 1,
                                        !is.na(epi_2_usa11c_7_5) ~ 2,
                                        !is.na(epi_2_usa11c_7_7) ~ 3,
                                        !is.na(epi_2_usa11c_7_9) ~ 4,
                                        !is.na(epi_2_usa11c_7_11) ~ 5),
         epi_2_usa12b_num = case_when(!is.na(epi_2_usa12b_1) ~ 0,
                                      !is.na(epi_2_usa12b_2) ~ 1,
                                      !is.na(epi_2_usa12b_3) ~ 2,
                                      !is.na(epi_2_usa12b_4) ~ 3,
                                      !is.na(epi_2_usa12b_5) ~ 4,
                                      !is.na(epi_2_usa12b_6) ~ 5),
         epi_2_usa12c_1_num = case_when(!is.na(epi_2_usa12c_1_1) ~ 0,
                                        !is.na(epi_2_usa12c_1_3) ~ 1,
                                        !is.na(epi_2_usa12c_1_5) ~ 2,
                                        !is.na(epi_2_usa12c_1_7) ~ 3,
                                        !is.na(epi_2_usa12c_1_9) ~ 4,
                                        !is.na(epi_2_usa12c_1_11) ~ 5),
         epi_2_usa12c_2_num = case_when(!is.na(epi_2_usa12c_2_1) ~ 0,
                                        !is.na(epi_2_usa12c_2_3) ~ 1,
                                        !is.na(epi_2_usa12c_2_5) ~ 2,
                                        !is.na(epi_2_usa12c_2_7) ~ 3,
                                        !is.na(epi_2_usa12c_2_9) ~ 4,
                                        !is.na(epi_2_usa12c_2_11) ~ 5),
         epi_2_usa12c_3_num = case_when(!is.na(epi_2_usa12c_3_1) ~ 0,
                                        !is.na(epi_2_usa12c_3_3) ~ 1,
                                        !is.na(epi_2_usa12c_3_5) ~ 2,
                                        !is.na(epi_2_usa12c_3_7) ~ 3,
                                        !is.na(epi_2_usa12c_3_9) ~ 4,
                                        !is.na(epi_2_usa12c_3_11) ~ 5),
         epi_2_usa12c_4_num = case_when(!is.na(epi_2_usa12c_4_1) ~ 0,
                                        !is.na(epi_2_usa12c_4_3) ~ 1,
                                        !is.na(epi_2_usa12c_4_5) ~ 2,
                                        !is.na(epi_2_usa12c_4_7) ~ 3,
                                        !is.na(epi_2_usa12c_4_9) ~ 4,
                                        !is.na(epi_2_usa12c_4_11) ~ 5),
         epi_2_usa12c_5_num = case_when(!is.na(epi_2_usa12c_5_1) ~ 0,
                                        !is.na(epi_2_usa12c_5_3) ~ 1,
                                        !is.na(epi_2_usa12c_5_5) ~ 2,
                                        !is.na(epi_2_usa12c_5_7) ~ 3,
                                        !is.na(epi_2_usa12c_5_9) ~ 4,
                                        !is.na(epi_2_usa12c_5_11) ~ 5),
         epi_2_usa12c_6_num = case_when(!is.na(epi_2_usa12c_6_1) ~ 0,
                                        !is.na(epi_2_usa12c_6_3) ~ 1,
                                        !is.na(epi_2_usa12c_6_5) ~ 2,
                                        !is.na(epi_2_usa12c_6_7) ~ 3,
                                        !is.na(epi_2_usa12c_6_9) ~ 4,
                                        !is.na(epi_2_usa12c_6_11) ~ 5),
         epi_2_usa12c_7_num = case_when(!is.na(epi_2_usa12c_7_1) ~ 0,
                                        !is.na(epi_2_usa12c_7_3) ~ 1,
                                        !is.na(epi_2_usa12c_7_5) ~ 2,
                                        !is.na(epi_2_usa12c_7_7) ~ 3,
                                        !is.na(epi_2_usa12c_7_9) ~ 4,
                                        !is.na(epi_2_usa12c_7_11) ~ 5),
         epi_2_usa13b_num = case_when(!is.na(epi_2_usa13b_1) ~ 0,
                                      !is.na(epi_2_usa13b_2) ~ 1,
                                      !is.na(epi_2_usa13b_3) ~ 2,
                                      !is.na(epi_2_usa13b_4) ~ 3,
                                      !is.na(epi_2_usa13b_5) ~ 4,
                                      !is.na(epi_2_usa13b_6) ~ 5),
         epi_2_usa13c_1_num = case_when(!is.na(epi_2_usa13c_1_1) ~ 0,
                                        !is.na(epi_2_usa13c_1_3) ~ 1,
                                        !is.na(epi_2_usa13c_1_5) ~ 2,
                                        !is.na(epi_2_usa13c_1_7) ~ 3,
                                        !is.na(epi_2_usa13c_1_9) ~ 4,
                                        !is.na(epi_2_usa13c_1_11) ~ 5),
         epi_2_usa13c_2_num = case_when(!is.na(epi_2_usa13c_2_1) ~ 0,
                                        !is.na(epi_2_usa13c_2_3) ~ 1,
                                        !is.na(epi_2_usa13c_2_5) ~ 2,
                                        !is.na(epi_2_usa13c_2_7) ~ 3,
                                        !is.na(epi_2_usa13c_2_9) ~ 4,
                                        !is.na(epi_2_usa13c_2_11) ~ 5),
         epi_2_usa13c_3_num = case_when(!is.na(epi_2_usa13c_3_1) ~ 0,
                                        !is.na(epi_2_usa13c_3_3) ~ 1,
                                        !is.na(epi_2_usa13c_3_5) ~ 2,
                                        !is.na(epi_2_usa13c_3_7) ~ 3,
                                        !is.na(epi_2_usa13c_3_9) ~ 4,
                                        !is.na(epi_2_usa13c_3_11) ~ 5),
         epi_2_usa13c_4_num = case_when(!is.na(epi_2_usa13c_4_1) ~ 0,
                                        !is.na(epi_2_usa13c_4_3) ~ 1,
                                        !is.na(epi_2_usa13c_4_5) ~ 2,
                                        !is.na(epi_2_usa13c_4_7) ~ 3,
                                        !is.na(epi_2_usa13c_4_9) ~ 4,
                                        !is.na(epi_2_usa13c_4_11) ~ 5),
         epi_2_usa13c_5_num = case_when(!is.na(epi_2_usa13c_5_1) ~ 0,
                                        !is.na(epi_2_usa13c_5_3) ~ 1,
                                        !is.na(epi_2_usa13c_5_5) ~ 2,
                                        !is.na(epi_2_usa13c_5_7) ~ 3,
                                        !is.na(epi_2_usa13c_5_9) ~ 4,
                                        !is.na(epi_2_usa13c_5_11) ~ 5),
         epi_2_usa13c_6_num = case_when(!is.na(epi_2_usa13c_6_1) ~ 0,
                                        !is.na(epi_2_usa13c_6_3) ~ 1,
                                        !is.na(epi_2_usa13c_6_5) ~ 2,
                                        !is.na(epi_2_usa13c_6_7) ~ 3,
                                        !is.na(epi_2_usa13c_6_9) ~ 4,
                                        !is.na(epi_2_usa13c_6_11) ~ 5),
         epi_2_usa13c_7_num = case_when(!is.na(epi_2_usa13c_7_1) ~ 0,
                                        !is.na(epi_2_usa13c_7_3) ~ 1,
                                        !is.na(epi_2_usa13c_7_5) ~ 2,
                                        !is.na(epi_2_usa13c_7_7) ~ 3,
                                        !is.na(epi_2_usa13c_7_9) ~ 4,
                                        !is.na(epi_2_usa13c_7_11) ~ 5),
         epi_2_usa14b_num = case_when(!is.na(epi_2_usa14b_1) ~ 0,
                                      !is.na(epi_2_usa14b_2) ~ 1,
                                      !is.na(epi_2_usa14b_3) ~ 2,
                                      !is.na(epi_2_usa14b_4) ~ 3,
                                      !is.na(epi_2_usa14b_5) ~ 4,
                                      !is.na(epi_2_usa14b_6) ~ 5),
         epi_2_usa14c_1_num = case_when(!is.na(epi_2_usa14c_1_1) ~ 0,
                                        !is.na(epi_2_usa14c_1_3) ~ 1,
                                        !is.na(epi_2_usa14c_1_5) ~ 2,
                                        !is.na(epi_2_usa14c_1_7) ~ 3,
                                        !is.na(epi_2_usa14c_1_9) ~ 4,
                                        !is.na(epi_2_usa14c_1_11) ~ 5),
         epi_2_usa14c_2_num = case_when(!is.na(epi_2_usa14c_2_1) ~ 0,
                                        !is.na(epi_2_usa14c_2_3) ~ 1,
                                        !is.na(epi_2_usa14c_2_5) ~ 2,
                                        !is.na(epi_2_usa14c_2_7) ~ 3,
                                        !is.na(epi_2_usa14c_2_9) ~ 4,
                                        !is.na(epi_2_usa14c_2_11) ~ 5),
         epi_2_usa14c_3_num = case_when(!is.na(epi_2_usa14c_3_1) ~ 0,
                                        !is.na(epi_2_usa14c_3_3) ~ 1,
                                        !is.na(epi_2_usa14c_3_5) ~ 2,
                                        !is.na(epi_2_usa14c_3_7) ~ 3,
                                        !is.na(epi_2_usa14c_3_9) ~ 4,
                                        !is.na(epi_2_usa14c_3_11) ~ 5),
         epi_2_usa14c_4_num = case_when(!is.na(epi_2_usa14c_4_1) ~ 0,
                                        !is.na(epi_2_usa14c_4_3) ~ 1,
                                        !is.na(epi_2_usa14c_4_5) ~ 2,
                                        !is.na(epi_2_usa14c_4_7) ~ 3,
                                        !is.na(epi_2_usa14c_4_9) ~ 4,
                                        !is.na(epi_2_usa14c_4_11) ~ 5),
         epi_2_usa14c_5_num = case_when(!is.na(epi_2_usa14c_5_1) ~ 0,
                                        !is.na(epi_2_usa14c_5_3) ~ 1,
                                        !is.na(epi_2_usa14c_5_5) ~ 2,
                                        !is.na(epi_2_usa14c_5_7) ~ 3,
                                        !is.na(epi_2_usa14c_5_9) ~ 4,
                                        !is.na(epi_2_usa14c_5_11) ~ 5),
         epi_2_usa14c_6_num = case_when(!is.na(epi_2_usa14c_6_1) ~ 0,
                                        !is.na(epi_2_usa14c_6_3) ~ 1,
                                        !is.na(epi_2_usa14c_6_5) ~ 2,
                                        !is.na(epi_2_usa14c_6_7) ~ 3,
                                        !is.na(epi_2_usa14c_6_9) ~ 4,
                                        !is.na(epi_2_usa14c_6_11) ~ 5),
         epi_2_usa14c_7_num = case_when(!is.na(epi_2_usa14c_7_1) ~ 0,
                                        !is.na(epi_2_usa14c_7_3) ~ 1,
                                        !is.na(epi_2_usa14c_7_5) ~ 2,
                                        !is.na(epi_2_usa14c_7_7) ~ 3,
                                        !is.na(epi_2_usa14c_7_9) ~ 4,
                                        !is.na(epi_2_usa14c_7_11) ~ 5),
         epi_2_usa15b_num = case_when(!is.na(epi_2_usa15b_1) ~ 0,
                                      !is.na(epi_2_usa15b_2) ~ 1,
                                      !is.na(epi_2_usa15b_3) ~ 2,
                                      !is.na(epi_2_usa15b_4) ~ 3,
                                      !is.na(epi_2_usa15b_5) ~ 4,
                                      !is.na(epi_2_usa15b_6) ~ 5),
         epi_2_usa15c_1_num = case_when(!is.na(epi_2_usa15c_1_1) ~ 0,
                                        !is.na(epi_2_usa15c_1_3) ~ 1,
                                        !is.na(epi_2_usa15c_1_5) ~ 2,
                                        !is.na(epi_2_usa15c_1_7) ~ 3,
                                        !is.na(epi_2_usa15c_1_9) ~ 4,
                                        !is.na(epi_2_usa15c_1_11) ~ 5),
         epi_2_usa15c_2_num = case_when(!is.na(epi_2_usa15c_2_1) ~ 0,
                                        !is.na(epi_2_usa15c_2_3) ~ 1,
                                        !is.na(epi_2_usa15c_2_5) ~ 2,
                                        !is.na(epi_2_usa15c_2_7) ~ 3,
                                        !is.na(epi_2_usa15c_2_9) ~ 4,
                                        !is.na(epi_2_usa15c_2_11) ~ 5),
         epi_2_usa15c_3_num = case_when(!is.na(epi_2_usa15c_3_1) ~ 0,
                                        !is.na(epi_2_usa15c_3_3) ~ 1,
                                        !is.na(epi_2_usa15c_3_5) ~ 2,
                                        !is.na(epi_2_usa15c_3_7) ~ 3,
                                        !is.na(epi_2_usa15c_3_9) ~ 4,
                                        !is.na(epi_2_usa15c_3_11) ~ 5),
         epi_2_usa15c_4_num = case_when(!is.na(epi_2_usa15c_4_1) ~ 0,
                                        !is.na(epi_2_usa15c_4_3) ~ 1,
                                        !is.na(epi_2_usa15c_4_5) ~ 2,
                                        !is.na(epi_2_usa15c_4_7) ~ 3,
                                        !is.na(epi_2_usa15c_4_9) ~ 4,
                                        !is.na(epi_2_usa15c_4_11) ~ 5),
         epi_2_usa15c_5_num = case_when(!is.na(epi_2_usa15c_5_1) ~ 0,
                                        !is.na(epi_2_usa15c_5_3) ~ 1,
                                        !is.na(epi_2_usa15c_5_5) ~ 2,
                                        !is.na(epi_2_usa15c_5_7) ~ 3,
                                        !is.na(epi_2_usa15c_5_9) ~ 4,
                                        !is.na(epi_2_usa15c_5_11) ~ 5),
         epi_2_usa15c_6_num = case_when(!is.na(epi_2_usa15c_6_1) ~ 0,
                                        !is.na(epi_2_usa15c_6_3) ~ 1,
                                        !is.na(epi_2_usa15c_6_5) ~ 2,
                                        !is.na(epi_2_usa15c_6_7) ~ 3,
                                        !is.na(epi_2_usa15c_6_9) ~ 4,
                                        !is.na(epi_2_usa15c_6_11) ~ 5),
         epi_2_usa15c_7_num = case_when(!is.na(epi_2_usa15c_7_1) ~ 0,
                                        !is.na(epi_2_usa15c_7_3) ~ 1,
                                        !is.na(epi_2_usa15c_7_5) ~ 2,
                                        !is.na(epi_2_usa15c_7_7) ~ 3,
                                        !is.na(epi_2_usa15c_7_9) ~ 4,
                                        !is.na(epi_2_usa15c_7_11) ~ 5),
         
         # GHA
         epi_2_gha11b_num = case_when(!is.na(epi_2_gha11b_1) ~ 0,
                                      !is.na(epi_2_gha11b_2) ~ 1,
                                      !is.na(epi_2_gha11b_3) ~ 2,
                                      !is.na(epi_2_gha11b_4) ~ 3,
                                      !is.na(epi_2_gha11b_5) ~ 4,
                                      !is.na(epi_2_gha11b_6) ~ 5),
         epi_2_gha11c_1_num = case_when(!is.na(epi_2_gha11c_1_1) ~ 0,
                                        !is.na(epi_2_gha11c_1_3) ~ 1,
                                        !is.na(epi_2_gha11c_1_5) ~ 2,
                                        !is.na(epi_2_gha11c_1_7) ~ 3,
                                        !is.na(epi_2_gha11c_1_9) ~ 4,
                                        !is.na(epi_2_gha11c_1_11) ~ 5),
         epi_2_gha11c_2_num = case_when(!is.na(epi_2_gha11c_2_1) ~ 0,
                                        !is.na(epi_2_gha11c_2_3) ~ 1,
                                        !is.na(epi_2_gha11c_2_5) ~ 2,
                                        !is.na(epi_2_gha11c_2_7) ~ 3,
                                        !is.na(epi_2_gha11c_2_9) ~ 4,
                                        !is.na(epi_2_gha11c_2_11) ~ 5),
         epi_2_gha11c_3_num = case_when(!is.na(epi_2_gha11c_3_1) ~ 0,
                                        !is.na(epi_2_gha11c_3_3) ~ 1,
                                        !is.na(epi_2_gha11c_3_5) ~ 2,
                                        !is.na(epi_2_gha11c_3_7) ~ 3,
                                        !is.na(epi_2_gha11c_3_9) ~ 4,
                                        !is.na(epi_2_gha11c_3_11) ~ 5),
         epi_2_gha11c_4_num = case_when(!is.na(epi_2_gha11c_4_1) ~ 0,
                                        !is.na(epi_2_gha11c_4_3) ~ 1,
                                        !is.na(epi_2_gha11c_4_5) ~ 2,
                                        !is.na(epi_2_gha11c_4_7) ~ 3,
                                        !is.na(epi_2_gha11c_4_9) ~ 4,
                                        !is.na(epi_2_gha11c_4_11) ~ 5),
         epi_2_gha11c_5_num = case_when(!is.na(epi_2_gha11c_5_1) ~ 0,
                                        !is.na(epi_2_gha11c_5_3) ~ 1,
                                        !is.na(epi_2_gha11c_5_5) ~ 2,
                                        !is.na(epi_2_gha11c_5_7) ~ 3,
                                        !is.na(epi_2_gha11c_5_9) ~ 4,
                                        !is.na(epi_2_gha11c_5_11) ~ 5),
         epi_2_gha11c_6_num = case_when(!is.na(epi_2_gha11c_6_1) ~ 0,
                                        !is.na(epi_2_gha11c_6_3) ~ 1,
                                        !is.na(epi_2_gha11c_6_5) ~ 2,
                                        !is.na(epi_2_gha11c_6_7) ~ 3,
                                        !is.na(epi_2_gha11c_6_9) ~ 4,
                                        !is.na(epi_2_gha11c_6_11) ~ 5),
         epi_2_gha11c_7_num = case_when(!is.na(epi_2_gha11c_7_1) ~ 0,
                                        !is.na(epi_2_gha11c_7_3) ~ 1,
                                        !is.na(epi_2_gha11c_7_5) ~ 2,
                                        !is.na(epi_2_gha11c_7_7) ~ 3,
                                        !is.na(epi_2_gha11c_7_9) ~ 4,
                                        !is.na(epi_2_gha11c_7_11) ~ 5),
         epi_2_gha12b_num = case_when(!is.na(epi_2_gha12b_1) ~ 0,
                                      !is.na(epi_2_gha12b_2) ~ 1,
                                      !is.na(epi_2_gha12b_3) ~ 2,
                                      !is.na(epi_2_gha12b_4) ~ 3,
                                      !is.na(epi_2_gha12b_5) ~ 4,
                                      !is.na(epi_2_gha12b_6) ~ 5),
         epi_2_gha12c_1_num = case_when(!is.na(epi_2_gha12c_1_1) ~ 0,
                                        !is.na(epi_2_gha12c_1_3) ~ 1,
                                        !is.na(epi_2_gha12c_1_5) ~ 2,
                                        !is.na(epi_2_gha12c_1_7) ~ 3,
                                        !is.na(epi_2_gha12c_1_9) ~ 4,
                                        !is.na(epi_2_gha12c_1_11) ~ 5),
         epi_2_gha12c_2_num = case_when(!is.na(epi_2_gha12c_2_1) ~ 0,
                                        !is.na(epi_2_gha12c_2_3) ~ 1,
                                        !is.na(epi_2_gha12c_2_5) ~ 2,
                                        !is.na(epi_2_gha12c_2_7) ~ 3,
                                        !is.na(epi_2_gha12c_2_9) ~ 4,
                                        !is.na(epi_2_gha12c_2_11) ~ 5),
         epi_2_gha12c_3_num = case_when(!is.na(epi_2_gha12c_3_1) ~ 0,
                                        !is.na(epi_2_gha12c_3_3) ~ 1,
                                        !is.na(epi_2_gha12c_3_5) ~ 2,
                                        !is.na(epi_2_gha12c_3_7) ~ 3,
                                        !is.na(epi_2_gha12c_3_9) ~ 4,
                                        !is.na(epi_2_gha12c_3_11) ~ 5),
         epi_2_gha12c_4_num = case_when(!is.na(epi_2_gha12c_4_1) ~ 0,
                                        !is.na(epi_2_gha12c_4_3) ~ 1,
                                        !is.na(epi_2_gha12c_4_5) ~ 2,
                                        !is.na(epi_2_gha12c_4_7) ~ 3,
                                        !is.na(epi_2_gha12c_4_9) ~ 4,
                                        !is.na(epi_2_gha12c_4_11) ~ 5),
         epi_2_gha12c_5_num = case_when(!is.na(epi_2_gha12c_5_1) ~ 0,
                                        !is.na(epi_2_gha12c_5_3) ~ 1,
                                        !is.na(epi_2_gha12c_5_5) ~ 2,
                                        !is.na(epi_2_gha12c_5_7) ~ 3,
                                        !is.na(epi_2_gha12c_5_9) ~ 4,
                                        !is.na(epi_2_gha12c_5_11) ~ 5),
         epi_2_gha12c_6_num = case_when(!is.na(epi_2_gha12c_6_1) ~ 0,
                                        !is.na(epi_2_gha12c_6_3) ~ 1,
                                        !is.na(epi_2_gha12c_6_5) ~ 2,
                                        !is.na(epi_2_gha12c_6_7) ~ 3,
                                        !is.na(epi_2_gha12c_6_9) ~ 4,
                                        !is.na(epi_2_gha12c_6_11) ~ 5),
         epi_2_gha12c_7_num = case_when(!is.na(epi_2_gha12c_7_1) ~ 0,
                                        !is.na(epi_2_gha12c_7_3) ~ 1,
                                        !is.na(epi_2_gha12c_7_5) ~ 2,
                                        !is.na(epi_2_gha12c_7_7) ~ 3,
                                        !is.na(epi_2_gha12c_7_9) ~ 4,
                                        !is.na(epi_2_gha12c_7_11) ~ 5),
         epi_2_gha13b_num = case_when(!is.na(epi_2_gha13b_1) ~ 0,
                                      !is.na(epi_2_gha13b_2) ~ 1,
                                      !is.na(epi_2_gha13b_3) ~ 2,
                                      !is.na(epi_2_gha13b_4) ~ 3,
                                      !is.na(epi_2_gha13b_5) ~ 4,
                                      !is.na(epi_2_gha13b_6) ~ 5),
         epi_2_gha13c_1_num = case_when(!is.na(epi_2_gha13c_1_1) ~ 0,
                                        !is.na(epi_2_gha13c_1_3) ~ 1,
                                        !is.na(epi_2_gha13c_1_5) ~ 2,
                                        !is.na(epi_2_gha13c_1_7) ~ 3,
                                        !is.na(epi_2_gha13c_1_9) ~ 4,
                                        !is.na(epi_2_gha13c_1_11) ~ 5),
         epi_2_gha13c_2_num = case_when(!is.na(epi_2_gha13c_2_1) ~ 0,
                                        !is.na(epi_2_gha13c_2_3) ~ 1,
                                        !is.na(epi_2_gha13c_2_5) ~ 2,
                                        !is.na(epi_2_gha13c_2_7) ~ 3,
                                        !is.na(epi_2_gha13c_2_9) ~ 4,
                                        !is.na(epi_2_gha13c_2_11) ~ 5),
         epi_2_gha13c_3_num = case_when(!is.na(epi_2_gha13c_3_1) ~ 0,
                                        !is.na(epi_2_gha13c_3_3) ~ 1,
                                        !is.na(epi_2_gha13c_3_5) ~ 2,
                                        !is.na(epi_2_gha13c_3_7) ~ 3,
                                        !is.na(epi_2_gha13c_3_9) ~ 4,
                                        !is.na(epi_2_gha13c_3_11) ~ 5),
         epi_2_gha13c_4_num = case_when(!is.na(epi_2_gha13c_4_1) ~ 0,
                                        !is.na(epi_2_gha13c_4_3) ~ 1,
                                        !is.na(epi_2_gha13c_4_5) ~ 2,
                                        !is.na(epi_2_gha13c_4_7) ~ 3,
                                        !is.na(epi_2_gha13c_4_9) ~ 4,
                                        !is.na(epi_2_gha13c_4_11) ~ 5),
         epi_2_gha13c_5_num = case_when(!is.na(epi_2_gha13c_5_1) ~ 0,
                                        !is.na(epi_2_gha13c_5_3) ~ 1,
                                        !is.na(epi_2_gha13c_5_5) ~ 2,
                                        !is.na(epi_2_gha13c_5_7) ~ 3,
                                        !is.na(epi_2_gha13c_5_9) ~ 4,
                                        !is.na(epi_2_gha13c_5_11) ~ 5),
         epi_2_gha13c_6_num = case_when(!is.na(epi_2_gha13c_6_1) ~ 0,
                                        !is.na(epi_2_gha13c_6_3) ~ 1,
                                        !is.na(epi_2_gha13c_6_5) ~ 2,
                                        !is.na(epi_2_gha13c_6_7) ~ 3,
                                        !is.na(epi_2_gha13c_6_9) ~ 4,
                                        !is.na(epi_2_gha13c_6_11) ~ 5),
         epi_2_gha13c_7_num = case_when(!is.na(epi_2_gha13c_7_1) ~ 0,
                                        !is.na(epi_2_gha13c_7_3) ~ 1,
                                        !is.na(epi_2_gha13c_7_5) ~ 2,
                                        !is.na(epi_2_gha13c_7_7) ~ 3,
                                        !is.na(epi_2_gha13c_7_9) ~ 4,
                                        !is.na(epi_2_gha13c_7_11) ~ 5),
         epi_2_gha14b_num = case_when(!is.na(epi_2_gha14b_1) ~ 0,
                                      !is.na(epi_2_gha14b_2) ~ 1,
                                      !is.na(epi_2_gha14b_3) ~ 2,
                                      !is.na(epi_2_gha14b_4) ~ 3,
                                      !is.na(epi_2_gha14b_5) ~ 4,
                                      !is.na(epi_2_gha14b_6) ~ 5),
         epi_2_gha14c_1_num = case_when(!is.na(epi_2_gha14c_1_1) ~ 0,
                                        !is.na(epi_2_gha14c_1_3) ~ 1,
                                        !is.na(epi_2_gha14c_1_5) ~ 2,
                                        !is.na(epi_2_gha14c_1_7) ~ 3,
                                        !is.na(epi_2_gha14c_1_9) ~ 4,
                                        !is.na(epi_2_gha14c_1_11) ~ 5),
         epi_2_gha14c_2_num = case_when(!is.na(epi_2_gha14c_2_1) ~ 0,
                                        !is.na(epi_2_gha14c_2_3) ~ 1,
                                        !is.na(epi_2_gha14c_2_5) ~ 2,
                                        !is.na(epi_2_gha14c_2_7) ~ 3,
                                        !is.na(epi_2_gha14c_2_9) ~ 4,
                                        !is.na(epi_2_gha14c_2_11) ~ 5),
         epi_2_gha14c_3_num = case_when(!is.na(epi_2_gha14c_3_1) ~ 0,
                                        !is.na(epi_2_gha14c_3_3) ~ 1,
                                        !is.na(epi_2_gha14c_3_5) ~ 2,
                                        !is.na(epi_2_gha14c_3_7) ~ 3,
                                        !is.na(epi_2_gha14c_3_9) ~ 4,
                                        !is.na(epi_2_gha14c_3_11) ~ 5),
         epi_2_gha14c_4_num = case_when(!is.na(epi_2_gha14c_4_1) ~ 0,
                                        !is.na(epi_2_gha14c_4_3) ~ 1,
                                        !is.na(epi_2_gha14c_4_5) ~ 2,
                                        !is.na(epi_2_gha14c_4_7) ~ 3,
                                        !is.na(epi_2_gha14c_4_9) ~ 4,
                                        !is.na(epi_2_gha14c_4_11) ~ 5),
         epi_2_gha14c_5_num = case_when(!is.na(epi_2_gha14c_5_1) ~ 0,
                                        !is.na(epi_2_gha14c_5_3) ~ 1,
                                        !is.na(epi_2_gha14c_5_5) ~ 2,
                                        !is.na(epi_2_gha14c_5_7) ~ 3,
                                        !is.na(epi_2_gha14c_5_9) ~ 4,
                                        !is.na(epi_2_gha14c_5_11) ~ 5),
         epi_2_gha14c_6_num = case_when(!is.na(epi_2_gha14c_6_1) ~ 0,
                                        !is.na(epi_2_gha14c_6_3) ~ 1,
                                        !is.na(epi_2_gha14c_6_5) ~ 2,
                                        !is.na(epi_2_gha14c_6_7) ~ 3,
                                        !is.na(epi_2_gha14c_6_9) ~ 4,
                                        !is.na(epi_2_gha14c_6_11) ~ 5),
         epi_2_gha14c_7_num = case_when(!is.na(epi_2_gha14c_7_1) ~ 0,
                                        !is.na(epi_2_gha14c_7_3) ~ 1,
                                        !is.na(epi_2_gha14c_7_5) ~ 2,
                                        !is.na(epi_2_gha14c_7_7) ~ 3,
                                        !is.na(epi_2_gha14c_7_9) ~ 4,
                                        !is.na(epi_2_gha14c_7_11) ~ 5),
         epi_2_gha15b_num = case_when(!is.na(epi_2_gha15b_1) ~ 0,
                                      !is.na(epi_2_gha15b_2) ~ 1,
                                      !is.na(epi_2_gha15b_3) ~ 2,
                                      !is.na(epi_2_gha15b_4) ~ 3,
                                      !is.na(epi_2_gha15b_5) ~ 4,
                                      !is.na(epi_2_gha15b_6) ~ 5),
         epi_2_gha15c_1_num = case_when(!is.na(epi_2_gha15c_1_1) ~ 0,
                                        !is.na(epi_2_gha15c_1_3) ~ 1,
                                        !is.na(epi_2_gha15c_1_5) ~ 2,
                                        !is.na(epi_2_gha15c_1_7) ~ 3,
                                        !is.na(epi_2_gha15c_1_9) ~ 4,
                                        !is.na(epi_2_gha15c_1_11) ~ 5),
         epi_2_gha15c_2_num = case_when(!is.na(epi_2_gha15c_2_1) ~ 0,
                                        !is.na(epi_2_gha15c_2_3) ~ 1,
                                        !is.na(epi_2_gha15c_2_5) ~ 2,
                                        !is.na(epi_2_gha15c_2_7) ~ 3,
                                        !is.na(epi_2_gha15c_2_9) ~ 4,
                                        !is.na(epi_2_gha15c_2_11) ~ 5),
         epi_2_gha15c_3_num = case_when(!is.na(epi_2_gha15c_3_1) ~ 0,
                                        !is.na(epi_2_gha15c_3_3) ~ 1,
                                        !is.na(epi_2_gha15c_3_5) ~ 2,
                                        !is.na(epi_2_gha15c_3_7) ~ 3,
                                        !is.na(epi_2_gha15c_3_9) ~ 4,
                                        !is.na(epi_2_gha15c_3_11) ~ 5),
         epi_2_gha15c_4_num = case_when(!is.na(epi_2_gha15c_4_1) ~ 0,
                                        !is.na(epi_2_gha15c_4_3) ~ 1,
                                        !is.na(epi_2_gha15c_4_5) ~ 2,
                                        !is.na(epi_2_gha15c_4_7) ~ 3,
                                        !is.na(epi_2_gha15c_4_9) ~ 4,
                                        !is.na(epi_2_gha15c_4_11) ~ 5),
         epi_2_gha15c_5_num = case_when(!is.na(epi_2_gha15c_5_1) ~ 0,
                                        !is.na(epi_2_gha15c_5_3) ~ 1,
                                        !is.na(epi_2_gha15c_5_5) ~ 2,
                                        !is.na(epi_2_gha15c_5_7) ~ 3,
                                        !is.na(epi_2_gha15c_5_9) ~ 4,
                                        !is.na(epi_2_gha15c_5_11) ~ 5),
         epi_2_gha15c_6_num = case_when(!is.na(epi_2_gha15c_6_1) ~ 0,
                                        !is.na(epi_2_gha15c_6_3) ~ 1,
                                        !is.na(epi_2_gha15c_6_5) ~ 2,
                                        !is.na(epi_2_gha15c_6_7) ~ 3,
                                        !is.na(epi_2_gha15c_6_9) ~ 4,
                                        !is.na(epi_2_gha15c_6_11) ~ 5),
         epi_2_gha15c_7_num = case_when(!is.na(epi_2_gha15c_7_1) ~ 0,
                                        !is.na(epi_2_gha15c_7_3) ~ 1,
                                        !is.na(epi_2_gha15c_7_5) ~ 2,
                                        !is.na(epi_2_gha15c_7_7) ~ 3,
                                        !is.na(epi_2_gha15c_7_9) ~ 4,
                                        !is.na(epi_2_gha15c_7_11) ~ 5),
         
         # CHN
         epi_2_chn11b_num = case_when(!is.na(epi_2_chn11b_1) ~ 0,
                                      !is.na(epi_2_chn11b_2) ~ 1,
                                      !is.na(epi_2_chn11b_3) ~ 2,
                                      !is.na(epi_2_chn11b_4) ~ 3,
                                      !is.na(epi_2_chn11b_5) ~ 4,
                                      !is.na(epi_2_chn11b_6) ~ 5),
         epi_2_chn12b_num = case_when(!is.na(epi_2_chn12b_1) ~ 0,
                                      !is.na(epi_2_chn12b_2) ~ 1,
                                      !is.na(epi_2_chn12b_3) ~ 2,
                                      !is.na(epi_2_chn12b_4) ~ 3,
                                      !is.na(epi_2_chn12b_5) ~ 4,
                                      !is.na(epi_2_chn12b_6) ~ 5),
         epi_2_chn13b_num = case_when(!is.na(epi_2_chn13b_1) ~ 0,
                                      !is.na(epi_2_chn13b_2) ~ 1,
                                      !is.na(epi_2_chn13b_3) ~ 2,
                                      !is.na(epi_2_chn13b_4) ~ 3,
                                      !is.na(epi_2_chn13b_5) ~ 4,
                                      !is.na(epi_2_chn13b_6) ~ 5),
         epi_2_chn14b_num = case_when(!is.na(epi_2_chn14b_1) ~ 0,
                                      !is.na(epi_2_chn14b_2) ~ 1,
                                      !is.na(epi_2_chn14b_3) ~ 2,
                                      !is.na(epi_2_chn14b_4) ~ 3,
                                      !is.na(epi_2_chn14b_5) ~ 4,
                                      !is.na(epi_2_chn14b_6) ~ 5),
         epi_2_chn15b_num = case_when(!is.na(epi_2_chn15b_1) ~ 0,
                                      !is.na(epi_2_chn15b_2) ~ 1,
                                      !is.na(epi_2_chn15b_3) ~ 2,
                                      !is.na(epi_2_chn15b_4) ~ 3,
                                      !is.na(epi_2_chn15b_5) ~ 4,
                                      !is.na(epi_2_chn15b_6) ~ 5),
         
         # VUT
         epi_2_vut11b_num = case_when(!is.na(epi_2_vut11b_1) ~ 0,
                                      !is.na(epi_2_vut11b_2) ~ 1,
                                      !is.na(epi_2_vut11b_3) ~ 2,
                                      !is.na(epi_2_vut11b_4) ~ 3,
                                      !is.na(epi_2_vut11b_5) ~ 4,
                                      !is.na(epi_2_vut11b_6) ~ 5),
         epi_2_vut12b_num = case_when(!is.na(epi_2_vut12b_1) ~ 0,
                                      !is.na(epi_2_vut12b_2) ~ 1,
                                      !is.na(epi_2_vut12b_3) ~ 2,
                                      !is.na(epi_2_vut12b_4) ~ 3,
                                      !is.na(epi_2_vut12b_5) ~ 4,
                                      !is.na(epi_2_vut12b_6) ~ 5),
         epi_2_vut13b_num = case_when(!is.na(epi_2_vut13b_1) ~ 0,
                                      !is.na(epi_2_vut13b_2) ~ 1,
                                      !is.na(epi_2_vut13b_3) ~ 2,
                                      !is.na(epi_2_vut13b_4) ~ 3,
                                      !is.na(epi_2_vut13b_5) ~ 4,
                                      !is.na(epi_2_vut13b_6) ~ 5),
         epi_2_vut14b_num = case_when(!is.na(epi_2_vut14b_1) ~ 0,
                                      !is.na(epi_2_vut14b_2) ~ 1,
                                      !is.na(epi_2_vut14b_3) ~ 2,
                                      !is.na(epi_2_vut14b_4) ~ 3,
                                      !is.na(epi_2_vut14b_5) ~ 4,
                                      !is.na(epi_2_vut14b_6) ~ 5),
         epi_2_vut15b_num = case_when(!is.na(epi_2_vut15b_1) ~ 0,
                                      !is.na(epi_2_vut15b_2) ~ 1,
                                      !is.na(epi_2_vut15b_3) ~ 2,
                                      !is.na(epi_2_vut15b_4) ~ 3,
                                      !is.na(epi_2_vut15b_5) ~ 4,
                                      !is.na(epi_2_vut15b_6) ~ 5),
         
         # THL
         epi_2_thl12a_a_1_num = case_when(!is.na(epi_2_thl12a_a_1_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_1_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_1_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_1_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_1_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_1_11) ~ 5),
         epi_2_thl12a_a_2_num = case_when(!is.na(epi_2_thl12a_a_2_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_2_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_2_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_2_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_2_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_2_11) ~ 5),
         epi_2_thl12a_a_3_num = case_when(!is.na(epi_2_thl12a_a_3_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_3_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_3_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_3_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_3_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_3_11) ~ 5),
         epi_2_thl12a_a_4_num = case_when(!is.na(epi_2_thl12a_a_4_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_4_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_4_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_4_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_4_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_4_11) ~ 5),
         epi_2_thl12a_a_5_num = case_when(!is.na(epi_2_thl12a_a_5_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_5_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_5_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_5_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_5_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_5_11) ~ 5),
         epi_2_thl12a_a_6_num = case_when(!is.na(epi_2_thl12a_a_6_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_6_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_6_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_6_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_6_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_6_11) ~ 5),
         epi_2_thl12a_a_7_num = case_when(!is.na(epi_2_thl12a_a_7_1) ~ 0,
                                          !is.na(epi_2_thl12a_a_7_3) ~ 1,
                                          !is.na(epi_2_thl12a_a_7_5) ~ 2,
                                          !is.na(epi_2_thl12a_a_7_7) ~ 3,
                                          !is.na(epi_2_thl12a_a_7_9) ~ 4,
                                          !is.na(epi_2_thl12a_a_7_11) ~ 5),
         
         epi_2_thl12b_b_1_num = case_when(!is.na(epi_2_thl12b_b_1_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_1_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_1_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_1_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_1_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_1_11) ~ 5),
         epi_2_thl12b_b_2_num = case_when(!is.na(epi_2_thl12b_b_2_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_2_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_2_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_2_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_2_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_2_11) ~ 5),
         epi_2_thl12b_b_3_num = case_when(!is.na(epi_2_thl12b_b_3_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_3_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_3_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_3_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_3_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_3_11) ~ 5),
         epi_2_thl12b_b_4_num = case_when(!is.na(epi_2_thl12b_b_4_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_4_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_4_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_4_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_4_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_4_11) ~ 5),
         epi_2_thl12b_b_5_num = case_when(!is.na(epi_2_thl12b_b_5_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_5_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_5_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_5_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_5_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_5_11) ~ 5),
         epi_2_thl12b_b_6_num = case_when(!is.na(epi_2_thl12b_b_6_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_6_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_6_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_6_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_6_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_6_11) ~ 5),
         epi_2_thl12b_b_7_num = case_when(!is.na(epi_2_thl12b_b_7_1) ~ 0,
                                          !is.na(epi_2_thl12b_b_7_3) ~ 1,
                                          !is.na(epi_2_thl12b_b_7_5) ~ 2,
                                          !is.na(epi_2_thl12b_b_7_7) ~ 3,
                                          !is.na(epi_2_thl12b_b_7_9) ~ 4,
                                          !is.na(epi_2_thl12b_b_7_11) ~ 5),
         
         epi_2_thl12c_c_1_num = case_when(!is.na(epi_2_thl12c_c_1_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_1_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_1_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_1_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_1_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_1_11) ~ 5),
         epi_2_thl12c_c_2_num = case_when(!is.na(epi_2_thl12c_c_2_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_2_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_2_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_2_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_2_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_2_11) ~ 5),
         epi_2_thl12c_c_3_num = case_when(!is.na(epi_2_thl12c_c_3_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_3_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_3_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_3_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_3_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_3_11) ~ 5),
         epi_2_thl12c_c_4_num = case_when(!is.na(epi_2_thl12c_c_4_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_4_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_4_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_4_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_4_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_4_11) ~ 5),
         epi_2_thl12c_c_5_num = case_when(!is.na(epi_2_thl12c_c_5_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_5_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_5_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_5_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_5_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_5_11) ~ 5),
         epi_2_thl12c_c_6_num = case_when(!is.na(epi_2_thl12c_c_6_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_6_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_6_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_6_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_6_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_6_11) ~ 5),
         epi_2_thl12c_c_7_num = case_when(!is.na(epi_2_thl12c_c_7_1) ~ 0,
                                          !is.na(epi_2_thl12c_c_7_3) ~ 1,
                                          !is.na(epi_2_thl12c_c_7_5) ~ 2,
                                          !is.na(epi_2_thl12c_c_7_7) ~ 3,
                                          !is.na(epi_2_thl12c_c_7_9) ~ 4,
                                          !is.na(epi_2_thl12c_c_7_11) ~ 5),
         
         epi_2_thl12d_d_1_num = case_when(!is.na(epi_2_thl12d_d_1_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_1_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_1_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_1_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_1_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_1_11) ~ 5),
         epi_2_thl12d_d_2_num = case_when(!is.na(epi_2_thl12d_d_2_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_2_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_2_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_2_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_2_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_2_11) ~ 5),
         epi_2_thl12d_d_3_num = case_when(!is.na(epi_2_thl12d_d_3_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_3_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_3_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_3_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_3_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_3_11) ~ 5),
         epi_2_thl12d_d_4_num = case_when(!is.na(epi_2_thl12d_d_4_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_4_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_4_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_4_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_4_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_4_11) ~ 5),
         epi_2_thl12d_d_5_num = case_when(!is.na(epi_2_thl12d_d_5_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_5_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_5_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_5_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_5_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_5_11) ~ 5),
         epi_2_thl12d_d_6_num = case_when(!is.na(epi_2_thl12d_d_6_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_6_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_6_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_6_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_6_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_6_11) ~ 5),
         epi_2_thl12d_d_7_num = case_when(!is.na(epi_2_thl12d_d_7_1) ~ 0,
                                          !is.na(epi_2_thl12d_d_7_3) ~ 1,
                                          !is.na(epi_2_thl12d_d_7_5) ~ 2,
                                          !is.na(epi_2_thl12d_d_7_7) ~ 3,
                                          !is.na(epi_2_thl12d_d_7_9) ~ 4,
                                          !is.na(epi_2_thl12d_d_7_11) ~ 5),
         
         epi_2_thl12e_e_1_num = case_when(!is.na(epi_2_thl12e_e_1_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_1_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_1_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_1_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_1_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_1_11) ~ 5),
         epi_2_thl12e_e_2_num = case_when(!is.na(epi_2_thl12e_e_2_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_2_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_2_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_2_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_2_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_2_11) ~ 5),
         epi_2_thl12e_e_3_num = case_when(!is.na(epi_2_thl12e_e_3_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_3_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_3_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_3_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_3_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_3_11) ~ 5),
         epi_2_thl12e_e_4_num = case_when(!is.na(epi_2_thl12e_e_4_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_4_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_4_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_4_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_4_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_4_11) ~ 5),
         epi_2_thl12e_e_5_num = case_when(!is.na(epi_2_thl12e_e_5_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_5_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_5_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_5_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_5_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_5_11) ~ 5),
         epi_2_thl12e_e_6_num = case_when(!is.na(epi_2_thl12e_e_6_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_6_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_6_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_6_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_6_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_6_11) ~ 5),
         epi_2_thl12e_e_7_num = case_when(!is.na(epi_2_thl12e_e_7_1) ~ 0,
                                          !is.na(epi_2_thl12e_e_7_3) ~ 1,
                                          !is.na(epi_2_thl12e_e_7_5) ~ 2,
                                          !is.na(epi_2_thl12e_e_7_7) ~ 3,
                                          !is.na(epi_2_thl12e_e_7_9) ~ 4,
                                          !is.na(epi_2_thl12e_e_7_11) ~ 5),
         
         epi_2_thl12f_f_1_num = case_when(!is.na(epi_2_thl12f_f_1_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_1_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_1_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_1_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_1_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_1_11) ~ 5),
         epi_2_thl12f_f_2_num = case_when(!is.na(epi_2_thl12f_f_2_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_2_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_2_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_2_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_2_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_2_11) ~ 5),
         epi_2_thl12f_f_3_num = case_when(!is.na(epi_2_thl12f_f_3_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_3_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_3_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_3_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_3_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_3_11) ~ 5),
         epi_2_thl12f_f_4_num = case_when(!is.na(epi_2_thl12f_f_4_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_4_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_4_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_4_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_4_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_4_11) ~ 5),
         epi_2_thl12f_f_5_num = case_when(!is.na(epi_2_thl12f_f_5_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_5_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_5_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_5_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_5_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_5_11) ~ 5),
         epi_2_thl12f_f_6_num = case_when(!is.na(epi_2_thl12f_f_6_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_6_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_6_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_6_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_6_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_6_11) ~ 5),
         epi_2_thl12f_f_7_num = case_when(!is.na(epi_2_thl12f_f_7_1) ~ 0,
                                          !is.na(epi_2_thl12f_f_7_3) ~ 1,
                                          !is.na(epi_2_thl12f_f_7_5) ~ 2,
                                          !is.na(epi_2_thl12f_f_7_7) ~ 3,
                                          !is.na(epi_2_thl12f_f_7_9) ~ 4,
                                          !is.na(epi_2_thl12f_f_7_11) ~ 5),
         
         epi_2_thl12g_g_1_num = case_when(!is.na(epi_2_thl12g_g_1_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_1_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_1_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_1_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_1_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_1_11) ~ 5),
         epi_2_thl12g_g_2_num = case_when(!is.na(epi_2_thl12g_g_2_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_2_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_2_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_2_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_2_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_2_11) ~ 5),
         epi_2_thl12g_g_3_num = case_when(!is.na(epi_2_thl12g_g_3_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_3_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_3_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_3_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_3_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_3_11) ~ 5),
         epi_2_thl12g_g_4_num = case_when(!is.na(epi_2_thl12g_g_4_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_4_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_4_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_4_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_4_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_4_11) ~ 5),
         epi_2_thl12g_g_5_num = case_when(!is.na(epi_2_thl12g_g_5_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_5_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_5_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_5_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_5_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_5_11) ~ 5),
         epi_2_thl12g_g_6_num = case_when(!is.na(epi_2_thl12g_g_6_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_6_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_6_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_6_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_6_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_6_11) ~ 5),
         epi_2_thl12g_g_7_num = case_when(!is.na(epi_2_thl12g_g_7_1) ~ 0,
                                          !is.na(epi_2_thl12g_g_7_3) ~ 1,
                                          !is.na(epi_2_thl12g_g_7_5) ~ 2,
                                          !is.na(epi_2_thl12g_g_7_7) ~ 3,
                                          !is.na(epi_2_thl12g_g_7_9) ~ 4,
                                          !is.na(epi_2_thl12g_g_7_11) ~ 5),
         
         epi_2_thl12h_h_1_num = case_when(!is.na(epi_2_thl12h_h_1_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_1_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_1_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_1_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_1_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_1_11) ~ 5),
         epi_2_thl12h_h_2_num = case_when(!is.na(epi_2_thl12h_h_2_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_2_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_2_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_2_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_2_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_2_11) ~ 5),
         epi_2_thl12h_h_3_num = case_when(!is.na(epi_2_thl12h_h_3_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_3_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_3_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_3_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_3_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_3_11) ~ 5),
         epi_2_thl12h_h_4_num = case_when(!is.na(epi_2_thl12h_h_4_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_4_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_4_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_4_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_4_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_4_11) ~ 5),
         epi_2_thl12h_h_5_num = case_when(!is.na(epi_2_thl12h_h_5_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_5_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_5_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_5_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_5_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_5_11) ~ 5),
         epi_2_thl12h_h_6_num = case_when(!is.na(epi_2_thl12h_h_6_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_6_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_6_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_6_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_6_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_6_11) ~ 5),
         epi_2_thl12h_h_7_num = case_when(!is.na(epi_2_thl12h_h_7_1) ~ 0,
                                          !is.na(epi_2_thl12h_h_7_3) ~ 1,
                                          !is.na(epi_2_thl12h_h_7_5) ~ 2,
                                          !is.na(epi_2_thl12h_h_7_7) ~ 3,
                                          !is.na(epi_2_thl12h_h_7_9) ~ 4,
                                          !is.na(epi_2_thl12h_h_7_11) ~ 5),
         
         epi_2_thl12i_i_1_num = case_when(!is.na(epi_2_thl12i_i_1_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_1_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_1_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_1_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_1_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_1_11) ~ 5),
         epi_2_thl12i_i_2_num = case_when(!is.na(epi_2_thl12i_i_2_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_2_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_2_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_2_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_2_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_2_11) ~ 5),
         epi_2_thl12i_i_3_num = case_when(!is.na(epi_2_thl12i_i_3_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_3_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_3_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_3_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_3_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_3_11) ~ 5),
         epi_2_thl12i_i_4_num = case_when(!is.na(epi_2_thl12i_i_4_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_4_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_4_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_4_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_4_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_4_11) ~ 5),
         epi_2_thl12i_i_5_num = case_when(!is.na(epi_2_thl12i_i_5_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_5_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_5_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_5_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_5_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_5_11) ~ 5),
         epi_2_thl12i_i_6_num = case_when(!is.na(epi_2_thl12i_i_6_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_6_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_6_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_6_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_6_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_6_11) ~ 5),
         epi_2_thl12i_i_7_num = case_when(!is.na(epi_2_thl12i_i_7_1) ~ 0,
                                          !is.na(epi_2_thl12i_i_7_3) ~ 1,
                                          !is.na(epi_2_thl12i_i_7_5) ~ 2,
                                          !is.na(epi_2_thl12i_i_7_7) ~ 3,
                                          !is.na(epi_2_thl12i_i_7_9) ~ 4,
                                          !is.na(epi_2_thl12i_i_7_11) ~ 5),
         
         epi_2_thl12j_j_1_num = case_when(!is.na(epi_2_thl12j_j_1_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_1_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_1_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_1_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_1_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_1_11) ~ 5),
         epi_2_thl12j_j_2_num = case_when(!is.na(epi_2_thl12j_j_2_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_2_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_2_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_2_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_2_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_2_11) ~ 5),
         epi_2_thl12j_j_3_num = case_when(!is.na(epi_2_thl12j_j_3_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_3_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_3_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_3_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_3_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_3_11) ~ 5),
         epi_2_thl12j_j_4_num = case_when(!is.na(epi_2_thl12j_j_4_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_4_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_4_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_4_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_4_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_4_11) ~ 5),
         epi_2_thl12j_j_5_num = case_when(!is.na(epi_2_thl12j_j_5_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_5_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_5_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_5_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_5_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_5_11) ~ 5),
         epi_2_thl12j_j_6_num = case_when(!is.na(epi_2_thl12j_j_6_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_6_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_6_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_6_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_6_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_6_11) ~ 5),
         epi_2_thl12j_j_7_num = case_when(!is.na(epi_2_thl12j_j_7_1) ~ 0,
                                          !is.na(epi_2_thl12j_j_7_3) ~ 1,
                                          !is.na(epi_2_thl12j_j_7_5) ~ 2,
                                          !is.na(epi_2_thl12j_j_7_7) ~ 3,
                                          !is.na(epi_2_thl12j_j_7_9) ~ 4,
                                          !is.na(epi_2_thl12j_j_7_11) ~ 5),
         
         epi_2_thl12k_k_1_num = case_when(!is.na(epi_2_thl12k_k_1_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_1_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_1_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_1_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_1_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_1_11) ~ 5),
         epi_2_thl12k_k_2_num = case_when(!is.na(epi_2_thl12k_k_2_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_2_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_2_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_2_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_2_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_2_11) ~ 5),
         epi_2_thl12k_k_3_num = case_when(!is.na(epi_2_thl12k_k_3_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_3_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_3_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_3_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_3_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_3_11) ~ 5),
         epi_2_thl12k_k_4_num = case_when(!is.na(epi_2_thl12k_k_4_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_4_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_4_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_4_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_4_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_4_11) ~ 5),
         epi_2_thl12k_k_5_num = case_when(!is.na(epi_2_thl12k_k_5_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_5_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_5_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_5_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_5_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_5_11) ~ 5),
         epi_2_thl12k_k_6_num = case_when(!is.na(epi_2_thl12k_k_6_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_6_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_6_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_6_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_6_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_6_11) ~ 5),
         epi_2_thl12k_k_7_num = case_when(!is.na(epi_2_thl12k_k_7_1) ~ 0,
                                          !is.na(epi_2_thl12k_k_7_3) ~ 1,
                                          !is.na(epi_2_thl12k_k_7_5) ~ 2,
                                          !is.na(epi_2_thl12k_k_7_7) ~ 3,
                                          !is.na(epi_2_thl12k_k_7_9) ~ 4,
                                          !is.na(epi_2_thl12k_k_7_11) ~ 5),
         
         epi_2_thl14a_a_1_num = case_when(!is.na(epi_2_thl14a_a_1_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_1_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_1_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_1_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_1_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_1_11) ~ 5),
         epi_2_thl14a_a_2_num = case_when(!is.na(epi_2_thl14a_a_2_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_2_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_2_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_2_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_2_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_2_11) ~ 5),
         epi_2_thl14a_a_3_num = case_when(!is.na(epi_2_thl14a_a_3_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_3_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_3_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_3_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_3_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_3_11) ~ 5),
         epi_2_thl14a_a_4_num = case_when(!is.na(epi_2_thl14a_a_4_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_4_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_4_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_4_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_4_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_4_11) ~ 5),
         epi_2_thl14a_a_5_num = case_when(!is.na(epi_2_thl14a_a_5_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_5_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_5_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_5_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_5_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_5_11) ~ 5),
         epi_2_thl14a_a_6_num = case_when(!is.na(epi_2_thl14a_a_6_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_6_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_6_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_6_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_6_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_6_11) ~ 5),
         epi_2_thl14a_a_7_num = case_when(!is.na(epi_2_thl14a_a_7_1) ~ 0,
                                          !is.na(epi_2_thl14a_a_7_3) ~ 1,
                                          !is.na(epi_2_thl14a_a_7_5) ~ 2,
                                          !is.na(epi_2_thl14a_a_7_7) ~ 3,
                                          !is.na(epi_2_thl14a_a_7_9) ~ 4,
                                          !is.na(epi_2_thl14a_a_7_11) ~ 5),
         
         epi_2_thl14b_b_1_num = case_when(!is.na(epi_2_thl14b_b_1_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_1_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_1_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_1_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_1_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_1_11) ~ 5),
         epi_2_thl14b_b_2_num = case_when(!is.na(epi_2_thl14b_b_2_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_2_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_2_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_2_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_2_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_2_11) ~ 5),
         epi_2_thl14b_b_3_num = case_when(!is.na(epi_2_thl14b_b_3_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_3_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_3_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_3_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_3_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_3_11) ~ 5),
         epi_2_thl14b_b_4_num = case_when(!is.na(epi_2_thl14b_b_4_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_4_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_4_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_4_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_4_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_4_11) ~ 5),
         epi_2_thl14b_b_5_num = case_when(!is.na(epi_2_thl14b_b_5_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_5_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_5_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_5_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_5_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_5_11) ~ 5),
         epi_2_thl14b_b_6_num = case_when(!is.na(epi_2_thl14b_b_6_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_6_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_6_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_6_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_6_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_6_11) ~ 5),
         epi_2_thl14b_b_7_num = case_when(!is.na(epi_2_thl14b_b_7_1) ~ 0,
                                          !is.na(epi_2_thl14b_b_7_3) ~ 1,
                                          !is.na(epi_2_thl14b_b_7_5) ~ 2,
                                          !is.na(epi_2_thl14b_b_7_7) ~ 3,
                                          !is.na(epi_2_thl14b_b_7_9) ~ 4,
                                          !is.na(epi_2_thl14b_b_7_11) ~ 5),
         
         epi_2_thl14c_c_1_num = case_when(!is.na(epi_2_thl14c_c_1_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_1_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_1_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_1_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_1_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_1_11) ~ 5),
         epi_2_thl14c_c_2_num = case_when(!is.na(epi_2_thl14c_c_2_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_2_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_2_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_2_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_2_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_2_11) ~ 5),
         epi_2_thl14c_c_3_num = case_when(!is.na(epi_2_thl14c_c_3_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_3_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_3_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_3_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_3_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_3_11) ~ 5),
         epi_2_thl14c_c_4_num = case_when(!is.na(epi_2_thl14c_c_4_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_4_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_4_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_4_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_4_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_4_11) ~ 5),
         epi_2_thl14c_c_5_num = case_when(!is.na(epi_2_thl14c_c_5_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_5_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_5_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_5_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_5_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_5_11) ~ 5),
         epi_2_thl14c_c_6_num = case_when(!is.na(epi_2_thl14c_c_6_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_6_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_6_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_6_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_6_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_6_11) ~ 5),
         epi_2_thl14c_c_7_num = case_when(!is.na(epi_2_thl14c_c_7_1) ~ 0,
                                          !is.na(epi_2_thl14c_c_7_3) ~ 1,
                                          !is.na(epi_2_thl14c_c_7_5) ~ 2,
                                          !is.na(epi_2_thl14c_c_7_7) ~ 3,
                                          !is.na(epi_2_thl14c_c_7_9) ~ 4,
                                          !is.na(epi_2_thl14c_c_7_11) ~ 5),
         
         epi_2_thl14d_d_1_num = case_when(!is.na(epi_2_thl14d_d_1_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_1_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_1_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_1_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_1_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_1_11) ~ 5),
         epi_2_thl14d_d_2_num = case_when(!is.na(epi_2_thl14d_d_2_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_2_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_2_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_2_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_2_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_2_11) ~ 5),
         epi_2_thl14d_d_3_num = case_when(!is.na(epi_2_thl14d_d_3_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_3_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_3_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_3_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_3_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_3_11) ~ 5),
         epi_2_thl14d_d_4_num = case_when(!is.na(epi_2_thl14d_d_4_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_4_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_4_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_4_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_4_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_4_11) ~ 5),
         epi_2_thl14d_d_5_num = case_when(!is.na(epi_2_thl14d_d_5_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_5_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_5_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_5_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_5_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_5_11) ~ 5),
         epi_2_thl14d_d_6_num = case_when(!is.na(epi_2_thl14d_d_6_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_6_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_6_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_6_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_6_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_6_11) ~ 5),
         epi_2_thl14d_d_7_num = case_when(!is.na(epi_2_thl14d_d_7_1) ~ 0,
                                          !is.na(epi_2_thl14d_d_7_3) ~ 1,
                                          !is.na(epi_2_thl14d_d_7_5) ~ 2,
                                          !is.na(epi_2_thl14d_d_7_7) ~ 3,
                                          !is.na(epi_2_thl14d_d_7_9) ~ 4,
                                          !is.na(epi_2_thl14d_d_7_11) ~ 5),
         
         epi_2_thl14e_e_1_num = case_when(!is.na(epi_2_thl14e_e_1_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_1_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_1_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_1_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_1_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_1_11) ~ 5),
         epi_2_thl14e_e_2_num = case_when(!is.na(epi_2_thl14e_e_2_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_2_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_2_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_2_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_2_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_2_11) ~ 5),
         epi_2_thl14e_e_3_num = case_when(!is.na(epi_2_thl14e_e_3_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_3_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_3_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_3_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_3_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_3_11) ~ 5),
         epi_2_thl14e_e_4_num = case_when(!is.na(epi_2_thl14e_e_4_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_4_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_4_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_4_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_4_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_4_11) ~ 5),
         epi_2_thl14e_e_5_num = case_when(!is.na(epi_2_thl14e_e_5_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_5_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_5_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_5_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_5_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_5_11) ~ 5),
         epi_2_thl14e_e_6_num = case_when(!is.na(epi_2_thl14e_e_6_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_6_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_6_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_6_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_6_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_6_11) ~ 5),
         epi_2_thl14e_e_7_num = case_when(!is.na(epi_2_thl14e_e_7_1) ~ 0,
                                          !is.na(epi_2_thl14e_e_7_3) ~ 1,
                                          !is.na(epi_2_thl14e_e_7_5) ~ 2,
                                          !is.na(epi_2_thl14e_e_7_7) ~ 3,
                                          !is.na(epi_2_thl14e_e_7_9) ~ 4,
                                          !is.na(epi_2_thl14e_e_7_11) ~ 5),
         
         `epi_2_thl#1_1_num` = case_when(!is.na(`epi_2_thl#1_1_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_1_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_1_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_1_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_1_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_1_11`) ~ 5),
         `epi_2_thl#1_2_num` = case_when(!is.na(`epi_2_thl#1_2_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_2_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_2_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_2_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_2_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_2_11`) ~ 5),
         `epi_2_thl#1_3_num` = case_when(!is.na(`epi_2_thl#1_3_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_3_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_3_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_3_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_3_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_3_11`) ~ 5),
         `epi_2_thl#1_4_num` = case_when(!is.na(`epi_2_thl#1_4_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_4_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_4_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_4_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_4_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_4_11`) ~ 5),
         `epi_2_thl#1_5_num` = case_when(!is.na(`epi_2_thl#1_5_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_5_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_5_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_5_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_5_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_5_11`) ~ 5),
         `epi_2_thl#1_6_num` = case_when(!is.na(`epi_2_thl#1_6_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_6_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_6_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_6_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_6_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_6_11`) ~ 5),
         `epi_2_thl#1_7_num` = case_when(!is.na(`epi_2_thl#1_7_1`) ~ 0,
                                         !is.na(`epi_2_thl#1_7_3`) ~ 1,
                                         !is.na(`epi_2_thl#1_7_5`) ~ 2,
                                         !is.na(`epi_2_thl#1_7_7`) ~ 3,
                                         !is.na(`epi_2_thl#1_7_9`) ~ 4,
                                         !is.na(`epi_2_thl#1_7_11`) ~ 5),
         
         `epi_2_thl#2_1_num` = case_when(!is.na(`epi_2_thl#2_1_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_1_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_1_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_1_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_1_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_1_11`) ~ 5),
         `epi_2_thl#2_2_num` = case_when(!is.na(`epi_2_thl#2_2_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_2_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_2_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_2_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_2_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_2_11`) ~ 5),
         `epi_2_thl#2_3_num` = case_when(!is.na(`epi_2_thl#2_3_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_3_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_3_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_3_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_3_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_3_11`) ~ 5),
         `epi_2_thl#2_4_num` = case_when(!is.na(`epi_2_thl#2_4_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_4_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_4_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_4_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_4_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_4_11`) ~ 5),
         `epi_2_thl#2_5_num` = case_when(!is.na(`epi_2_thl#2_5_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_5_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_5_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_5_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_5_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_5_11`) ~ 5),
         `epi_2_thl#2_6_num` = case_when(!is.na(`epi_2_thl#2_6_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_6_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_6_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_6_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_6_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_6_11`) ~ 5),
         `epi_2_thl#2_7_num` = case_when(!is.na(`epi_2_thl#2_7_1`) ~ 0,
                                         !is.na(`epi_2_thl#2_7_3`) ~ 1,
                                         !is.na(`epi_2_thl#2_7_5`) ~ 2,
                                         !is.na(`epi_2_thl#2_7_7`) ~ 3,
                                         !is.na(`epi_2_thl#2_7_9`) ~ 4,
                                         !is.na(`epi_2_thl#2_7_11`) ~ 5),
         
         `epi_2_thl#3_1_num` = case_when(!is.na(`epi_2_thl#3_1_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_1_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_1_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_1_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_1_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_1_11`) ~ 5),
         `epi_2_thl#3_2_num` = case_when(!is.na(`epi_2_thl#3_2_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_2_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_2_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_2_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_2_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_2_11`) ~ 5),
         `epi_2_thl#3_3_num` = case_when(!is.na(`epi_2_thl#3_3_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_3_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_3_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_3_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_3_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_3_11`) ~ 5),
         `epi_2_thl#3_4_num` = case_when(!is.na(`epi_2_thl#3_4_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_4_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_4_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_4_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_4_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_4_11`) ~ 5),
         `epi_2_thl#3_5_num` = case_when(!is.na(`epi_2_thl#3_5_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_5_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_5_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_5_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_5_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_5_11`) ~ 5),
         `epi_2_thl#3_6_num` = case_when(!is.na(`epi_2_thl#3_6_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_6_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_6_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_6_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_6_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_6_11`) ~ 5),
         `epi_2_thl#3_7_num` = case_when(!is.na(`epi_2_thl#3_7_1`) ~ 0,
                                         !is.na(`epi_2_thl#3_7_3`) ~ 1,
                                         !is.na(`epi_2_thl#3_7_5`) ~ 2,
                                         !is.na(`epi_2_thl#3_7_7`) ~ 3,
                                         !is.na(`epi_2_thl#3_7_9`) ~ 4,
                                         !is.na(`epi_2_thl#3_7_11`) ~ 5),
         
         epi_2_thl24b_num = case_when(!is.na(epi_2_thl24b_1) ~ 0,
                                      !is.na(epi_2_thl24b_2) ~ 1,
                                      !is.na(epi_2_thl24b_3) ~ 2,
                                      !is.na(epi_2_thl24b_4) ~ 3,
                                      !is.na(epi_2_thl24b_5) ~ 4,
                                      !is.na(epi_2_thl24b_6) ~ 5),
         
         # UNIVERSAL
         epi_2_16a_num = case_when(!is.na(epi_2_16a_1) ~ 0,
                                   !is.na(epi_2_16a_2) ~ 1,
                                   !is.na(epi_2_16a_3) ~ 2,
                                   !is.na(epi_2_16a_4) ~ 3,
                                   !is.na(epi_2_16a_5) ~ 4,
                                   !is.na(epi_2_16a_6) ~ 5),
         epi_2_17a_num = case_when(!is.na(epi_2_17a_1) ~ 0,
                                   !is.na(epi_2_17a_2) ~ 1,
                                   !is.na(epi_2_17a_3) ~ 2,
                                   !is.na(epi_2_17a_4) ~ 3,
                                   !is.na(epi_2_17a_5) ~ 4,
                                   !is.na(epi_2_17a_6) ~ 5),
         epi_2_18b_num = case_when(!is.na(epi_2_18b_1) ~ 0,
                                   !is.na(epi_2_18b_2) ~ 1,
                                   !is.na(epi_2_18b_3) ~ 2,
                                   !is.na(epi_2_18b_4) ~ 3,
                                   !is.na(epi_2_18b_5) ~ 4,
                                   !is.na(epi_2_18b_6) ~ 5),
         epi_2_19a_num = case_when(!is.na(epi_2_19a_1) ~ 0,
                                   !is.na(epi_2_19a_2) ~ 1,
                                   !is.na(epi_2_19a_3) ~ 2,
                                   !is.na(epi_2_19a_4) ~ 3,
                                   !is.na(epi_2_19a_5) ~ 4,
                                   !is.na(epi_2_19a_6) ~ 5),
         epi_2_20b_num = case_when(!is.na(epi_2_20b_1) ~ 0,
                                   !is.na(epi_2_20b_2) ~ 1,
                                   !is.na(epi_2_20b_3) ~ 2,
                                   !is.na(epi_2_20b_4) ~ 3,
                                   !is.na(epi_2_20b_5) ~ 4,
                                   !is.na(epi_2_20b_6) ~ 5),
         epi_2_22d_num = case_when(!is.na(epi_2_22d_1) ~ 0,
                                   !is.na(epi_2_22d_2) ~ 1,
                                   !is.na(epi_2_22d_3) ~ 2,
                                   !is.na(epi_2_22d_4) ~ 3,
                                   !is.na(epi_2_22d_5) ~ 4,
                                   !is.na(epi_2_22d_6) ~ 5),
         epi_2_22e_num = case_when(!is.na(epi_2_22e_1) ~ 0,
                                   !is.na(epi_2_22e_2) ~ 1,
                                   !is.na(epi_2_22e_3) ~ 2,
                                   !is.na(epi_2_22e_4) ~ 3,
                                   !is.na(epi_2_22e_5) ~ 4,
                                   !is.na(epi_2_22e_6) ~ 5),
         epi_2_23d_num = case_when(!is.na(epi_2_23d_1) ~ 0,
                                   !is.na(epi_2_23d_2) ~ 1,
                                   !is.na(epi_2_23d_3) ~ 2,
                                   !is.na(epi_2_23d_4) ~ 3,
                                   !is.na(epi_2_23d_5) ~ 4,
                                   !is.na(epi_2_23d_6) ~ 5)) %>%
  select(-c(epi_2_02a_1:epi_2_02a_7, epi_2_03e_1:epi_2_03e_7,
            epi_2_04a_1:epi_2_04a_7, epi_2_05a_1:epi_2_05a_7,
            epi_2_06d_1:epi_2_06d_7, epi_2_07a_1:epi_2_07a_7,
            epi_2_08b_1:epi_2_08b_7, epi_2_09b_1:epi_2_09b_7,
            epi_2_10b_1:epi_2_10b_7, 
            
            # USA
            epi_2_usa11b_1:epi_2_usa11b_7,
            epi_2_usa11c_1_1:epi_2_usa11c_1_11, 
            epi_2_usa11c_2_1:epi_2_usa11c_2_11,
            epi_2_usa11c_3_1:epi_2_usa11c_3_11,
            epi_2_usa11c_4_1:epi_2_usa11c_4_11,
            epi_2_usa11c_5_1:epi_2_usa11c_5_11,
            epi_2_usa11c_6_1:epi_2_usa11c_6_11,
            epi_2_usa11c_7_1:epi_2_usa11c_7_11, 
            epi_2_usa12b_1:epi_2_usa12b_7,
            epi_2_usa12c_1_1:epi_2_usa12c_1_11,
            epi_2_usa12c_2_1:epi_2_usa12c_2_11,
            epi_2_usa12c_3_1:epi_2_usa12c_3_11,
            epi_2_usa12c_4_1:epi_2_usa12c_4_11,
            epi_2_usa12c_5_1:epi_2_usa12c_5_11,
            epi_2_usa12c_6_1:epi_2_usa12c_6_11,
            epi_2_usa12c_7_1:epi_2_usa12c_7_11,
            epi_2_usa13b_1:epi_2_usa13b_7,
            epi_2_usa13c_1_1:epi_2_usa13c_1_11,
            epi_2_usa13c_2_1:epi_2_usa13c_2_11,
            epi_2_usa13c_3_1:epi_2_usa13c_3_11,
            epi_2_usa13c_4_1:epi_2_usa13c_4_11,
            epi_2_usa13c_5_1:epi_2_usa13c_5_11,
            epi_2_usa13c_6_1:epi_2_usa13c_6_11,
            epi_2_usa13c_7_1:epi_2_usa13c_7_11,
            epi_2_usa14b_1:epi_2_usa14b_7,
            epi_2_usa14c_1_1:epi_2_usa14c_1_11,
            epi_2_usa14c_2_1:epi_2_usa14c_2_11,
            epi_2_usa14c_3_1:epi_2_usa14c_3_11,
            epi_2_usa14c_4_1:epi_2_usa14c_4_11,
            epi_2_usa14c_5_1:epi_2_usa14c_5_11,
            epi_2_usa14c_6_1:epi_2_usa14c_6_11,
            epi_2_usa14c_7_1:epi_2_usa14c_7_11,
            epi_2_usa15b_1:epi_2_usa15b_7,
            epi_2_usa15c_1_1:epi_2_usa15c_1_11,
            epi_2_usa15c_2_1:epi_2_usa15c_2_11,
            epi_2_usa15c_3_1:epi_2_usa15c_3_11,
            epi_2_usa15c_4_1:epi_2_usa15c_4_11,
            epi_2_usa15c_5_1:epi_2_usa15c_5_11,
            epi_2_usa15c_6_1:epi_2_usa15c_6_11,
            epi_2_usa15c_7_1:epi_2_usa15c_7_11,
            
            # GHA
            epi_2_gha11b_1:epi_2_gha11b_7,
            epi_2_gha11c_1_1:epi_2_gha11c_1_11, 
            epi_2_gha11c_2_1:epi_2_gha11c_2_11,
            epi_2_gha11c_3_1:epi_2_gha11c_3_11,
            epi_2_gha11c_4_1:epi_2_gha11c_4_11,
            epi_2_gha11c_5_1:epi_2_gha11c_5_11,
            epi_2_gha11c_6_1:epi_2_gha11c_6_11,
            epi_2_gha11c_7_1:epi_2_gha11c_7_11, 
            epi_2_gha12b_1:epi_2_gha12b_7,
            epi_2_gha12c_1_1:epi_2_gha12c_1_11,
            epi_2_gha12c_2_1:epi_2_gha12c_2_11,
            epi_2_gha12c_3_1:epi_2_gha12c_3_11,
            epi_2_gha12c_4_1:epi_2_gha12c_4_11,
            epi_2_gha12c_5_1:epi_2_gha12c_5_11,
            epi_2_gha12c_6_1:epi_2_gha12c_6_11,
            epi_2_gha12c_7_1:epi_2_gha12c_7_11,
            epi_2_gha13b_1:epi_2_gha13b_7,
            epi_2_gha13c_1_1:epi_2_gha13c_1_11,
            epi_2_gha13c_2_1:epi_2_gha13c_2_11,
            epi_2_gha13c_3_1:epi_2_gha13c_3_11,
            epi_2_gha13c_4_1:epi_2_gha13c_4_11,
            epi_2_gha13c_5_1:epi_2_gha13c_5_11,
            epi_2_gha13c_6_1:epi_2_gha13c_6_11,
            epi_2_gha13c_7_1:epi_2_gha13c_7_11,
            epi_2_gha14b_1:epi_2_gha14b_7,
            epi_2_gha14c_1_1:epi_2_gha14c_1_11,
            epi_2_gha14c_2_1:epi_2_gha14c_2_11,
            epi_2_gha14c_3_1:epi_2_gha14c_3_11,
            epi_2_gha14c_4_1:epi_2_gha14c_4_11,
            epi_2_gha14c_5_1:epi_2_gha14c_5_11,
            epi_2_gha14c_6_1:epi_2_gha14c_6_11,
            epi_2_gha14c_7_1:epi_2_gha14c_7_11,
            epi_2_gha15b_1:epi_2_gha15b_7,
            epi_2_gha15c_1_1:epi_2_gha15c_1_11,
            epi_2_gha15c_2_1:epi_2_gha15c_2_11,
            epi_2_gha15c_3_1:epi_2_gha15c_3_11,
            epi_2_gha15c_4_1:epi_2_gha15c_4_11,
            epi_2_gha15c_5_1:epi_2_gha15c_5_11,
            epi_2_gha15c_6_1:epi_2_gha15c_6_11,
            epi_2_gha15c_7_1:epi_2_gha15c_7_11,
            
            # CHN
            epi_2_chn11b_1:epi_2_chn11b_7, epi_2_chn12b_1:epi_2_chn12b_7, 
            epi_2_chn13b_1:epi_2_chn13b_7, epi_2_chn14b_1:epi_2_chn14b_7, 
            epi_2_chn15b_1:epi_2_chn15b_7,
            
            # VUT
            epi_2_vut11b_1:epi_2_vut11b_7, epi_2_vut12b_1:epi_2_vut12b_7, 
            epi_2_vut13b_1:epi_2_vut13b_7, epi_2_vut14b_1:epi_2_vut14b_7, 
            epi_2_vut15b_1:epi_2_vut15b_7,
            
            # THL
            epi_2_thl12a_a_1_1:epi_2_thl12a_a_1_13,
            epi_2_thl12a_a_2_1:epi_2_thl12a_a_2_13,
            epi_2_thl12a_a_3_1:epi_2_thl12a_a_3_13,
            epi_2_thl12a_a_4_1:epi_2_thl12a_a_4_13,
            epi_2_thl12a_a_5_1:epi_2_thl12a_a_5_13,
            epi_2_thl12a_a_6_1:epi_2_thl12a_a_6_13,
            epi_2_thl12a_a_7_1:epi_2_thl12a_a_7_13,
            
            epi_2_thl12b_b_1_1:epi_2_thl12b_b_1_13,
            epi_2_thl12b_b_2_1:epi_2_thl12b_b_2_13,
            epi_2_thl12b_b_3_1:epi_2_thl12b_b_3_13,
            epi_2_thl12b_b_4_1:epi_2_thl12b_b_4_13,
            epi_2_thl12b_b_5_1:epi_2_thl12b_b_5_13,
            epi_2_thl12b_b_6_1:epi_2_thl12b_b_6_13,
            epi_2_thl12b_b_7_1:epi_2_thl12b_b_7_13,
            
            epi_2_thl12c_c_1_1:epi_2_thl12c_c_1_13,
            epi_2_thl12c_c_2_1:epi_2_thl12c_c_2_13,
            epi_2_thl12c_c_3_1:epi_2_thl12c_c_3_13,
            epi_2_thl12c_c_4_1:epi_2_thl12c_c_4_13,
            epi_2_thl12c_c_5_1:epi_2_thl12c_c_5_13,
            epi_2_thl12c_c_6_1:epi_2_thl12c_c_6_13,
            epi_2_thl12c_c_7_1:epi_2_thl12c_c_7_13,
            
            epi_2_thl12d_d_1_1:epi_2_thl12d_d_1_13,
            epi_2_thl12d_d_2_1:epi_2_thl12d_d_2_13,
            epi_2_thl12d_d_3_1:epi_2_thl12d_d_3_13,
            epi_2_thl12d_d_4_1:epi_2_thl12d_d_4_13,
            epi_2_thl12d_d_5_1:epi_2_thl12d_d_5_13,
            epi_2_thl12d_d_6_1:epi_2_thl12d_d_6_13,
            epi_2_thl12d_d_7_1:epi_2_thl12d_d_7_13,
            
            epi_2_thl12e_e_1_1:epi_2_thl12e_e_1_13,
            epi_2_thl12e_e_2_1:epi_2_thl12e_e_2_13,
            epi_2_thl12e_e_3_1:epi_2_thl12e_e_3_13,
            epi_2_thl12e_e_4_1:epi_2_thl12e_e_4_13,
            epi_2_thl12e_e_5_1:epi_2_thl12e_e_5_13,
            epi_2_thl12e_e_6_1:epi_2_thl12e_e_6_13,
            epi_2_thl12e_e_7_1:epi_2_thl12e_e_7_13,
            
            epi_2_thl12f_f_1_1:epi_2_thl12f_f_1_13,
            epi_2_thl12f_f_2_1:epi_2_thl12f_f_2_13,
            epi_2_thl12f_f_3_1:epi_2_thl12f_f_3_13,
            epi_2_thl12f_f_4_1:epi_2_thl12f_f_4_13,
            epi_2_thl12f_f_5_1:epi_2_thl12f_f_5_13,
            epi_2_thl12f_f_6_1:epi_2_thl12f_f_6_13,
            epi_2_thl12f_f_7_1:epi_2_thl12f_f_7_13,
            
            epi_2_thl12g_g_1_1:epi_2_thl12g_g_1_13,
            epi_2_thl12g_g_2_1:epi_2_thl12g_g_2_13,
            epi_2_thl12g_g_3_1:epi_2_thl12g_g_3_13,
            epi_2_thl12g_g_4_1:epi_2_thl12g_g_4_13,
            epi_2_thl12g_g_5_1:epi_2_thl12g_g_5_13,
            epi_2_thl12g_g_6_1:epi_2_thl12g_g_6_13,
            epi_2_thl12g_g_7_1:epi_2_thl12g_g_7_13,
            
            epi_2_thl12h_h_1_1:epi_2_thl12h_h_1_13,
            epi_2_thl12h_h_2_1:epi_2_thl12h_h_2_13,
            epi_2_thl12h_h_3_1:epi_2_thl12h_h_3_13,
            epi_2_thl12h_h_4_1:epi_2_thl12h_h_4_13,
            epi_2_thl12h_h_5_1:epi_2_thl12h_h_5_13,
            epi_2_thl12h_h_6_1:epi_2_thl12h_h_6_13,
            epi_2_thl12h_h_7_1:epi_2_thl12h_h_7_13,
            
            epi_2_thl12i_i_1_1:epi_2_thl12i_i_1_13,
            epi_2_thl12i_i_2_1:epi_2_thl12i_i_2_13,
            epi_2_thl12i_i_3_1:epi_2_thl12i_i_3_13,
            epi_2_thl12i_i_4_1:epi_2_thl12i_i_4_13,
            epi_2_thl12i_i_5_1:epi_2_thl12i_i_5_13,
            epi_2_thl12i_i_6_1:epi_2_thl12i_i_6_13,
            epi_2_thl12i_i_7_1:epi_2_thl12i_i_7_13,
            
            epi_2_thl12j_j_1_1:epi_2_thl12j_j_1_13,
            epi_2_thl12j_j_2_1:epi_2_thl12j_j_2_13,
            epi_2_thl12j_j_3_1:epi_2_thl12j_j_3_13,
            epi_2_thl12j_j_4_1:epi_2_thl12j_j_4_13,
            epi_2_thl12j_j_5_1:epi_2_thl12j_j_5_13,
            epi_2_thl12j_j_6_1:epi_2_thl12j_j_6_13,
            epi_2_thl12j_j_7_1:epi_2_thl12j_j_7_13,
            
            epi_2_thl12k_k_1_1:epi_2_thl12k_k_1_13,
            epi_2_thl12k_k_2_1:epi_2_thl12k_k_2_13,
            epi_2_thl12k_k_3_1:epi_2_thl12k_k_3_13,
            epi_2_thl12k_k_4_1:epi_2_thl12k_k_4_13,
            epi_2_thl12k_k_5_1:epi_2_thl12k_k_5_13,
            epi_2_thl12k_k_6_1:epi_2_thl12k_k_6_13,
            epi_2_thl12k_k_7_1:epi_2_thl12k_k_7_13,
            
            epi_2_thl14a_a_1_1:epi_2_thl14a_a_1_13,
            epi_2_thl14a_a_2_1:epi_2_thl14a_a_2_13,
            epi_2_thl14a_a_3_1:epi_2_thl14a_a_3_13,
            epi_2_thl14a_a_4_1:epi_2_thl14a_a_4_13,
            epi_2_thl14a_a_5_1:epi_2_thl14a_a_5_13,
            epi_2_thl14a_a_6_1:epi_2_thl14a_a_6_13,
            epi_2_thl14a_a_7_1:epi_2_thl14a_a_7_13,
            
            epi_2_thl14b_b_1_1:epi_2_thl14b_b_1_13,
            epi_2_thl14b_b_2_1:epi_2_thl14b_b_2_13,
            epi_2_thl14b_b_3_1:epi_2_thl14b_b_3_13,
            epi_2_thl14b_b_4_1:epi_2_thl14b_b_4_13,
            epi_2_thl14b_b_5_1:epi_2_thl14b_b_5_13,
            epi_2_thl14b_b_6_1:epi_2_thl14b_b_6_13,
            epi_2_thl14b_b_7_1:epi_2_thl14b_b_7_13,
            
            epi_2_thl14c_c_1_1:epi_2_thl14c_c_1_13,
            epi_2_thl14c_c_2_1:epi_2_thl14c_c_2_13,
            epi_2_thl14c_c_3_1:epi_2_thl14c_c_3_13,
            epi_2_thl14c_c_4_1:epi_2_thl14c_c_4_13,
            epi_2_thl14c_c_5_1:epi_2_thl14c_c_5_13,
            epi_2_thl14c_c_6_1:epi_2_thl14c_c_6_13,
            epi_2_thl14c_c_7_1:epi_2_thl14c_c_7_13,
            
            epi_2_thl14d_d_1_1:epi_2_thl14d_d_1_13,
            epi_2_thl14d_d_2_1:epi_2_thl14d_d_2_13,
            epi_2_thl14d_d_3_1:epi_2_thl14d_d_3_13,
            epi_2_thl14d_d_4_1:epi_2_thl14d_d_4_13,
            epi_2_thl14d_d_5_1:epi_2_thl14d_d_5_13,
            epi_2_thl14d_d_6_1:epi_2_thl14d_d_6_13,
            epi_2_thl14d_d_7_1:epi_2_thl14d_d_7_13,
            
            epi_2_thl14e_e_1_1:epi_2_thl14e_e_1_13,
            epi_2_thl14e_e_2_1:epi_2_thl14e_e_2_13,
            epi_2_thl14e_e_3_1:epi_2_thl14e_e_3_13,
            epi_2_thl14e_e_4_1:epi_2_thl14e_e_4_13,
            epi_2_thl14e_e_5_1:epi_2_thl14e_e_5_13,
            epi_2_thl14e_e_6_1:epi_2_thl14e_e_6_13,
            epi_2_thl14e_e_7_1:epi_2_thl14e_e_7_13,
            
            `epi_2_thl#1_1_1`:`epi_2_thl#1_1_13`,
            `epi_2_thl#1_2_1`:`epi_2_thl#1_2_13`,
            `epi_2_thl#1_3_1`:`epi_2_thl#1_3_13`,
            `epi_2_thl#1_4_1`:`epi_2_thl#1_4_13`,
            `epi_2_thl#1_5_1`:`epi_2_thl#1_5_13`,
            `epi_2_thl#1_6_1`:`epi_2_thl#1_6_13`,
            `epi_2_thl#1_7_1`:`epi_2_thl#1_7_13`,
            
            `epi_2_thl#2_1_1`:`epi_2_thl#2_1_13`,
            `epi_2_thl#2_2_1`:`epi_2_thl#2_2_13`,
            `epi_2_thl#2_3_1`:`epi_2_thl#2_3_13`,
            `epi_2_thl#2_4_1`:`epi_2_thl#2_4_13`,
            `epi_2_thl#2_5_1`:`epi_2_thl#2_5_13`,
            `epi_2_thl#2_6_1`:`epi_2_thl#2_6_13`,
            `epi_2_thl#2_7_1`:`epi_2_thl#2_7_13`,
            
            `epi_2_thl#3_1_1`:`epi_2_thl#3_1_13`,
            `epi_2_thl#3_2_1`:`epi_2_thl#3_2_13`,
            `epi_2_thl#3_3_1`:`epi_2_thl#3_3_13`,
            `epi_2_thl#3_4_1`:`epi_2_thl#3_4_13`,
            `epi_2_thl#3_5_1`:`epi_2_thl#3_5_13`,
            `epi_2_thl#3_6_1`:`epi_2_thl#3_6_13`,
            `epi_2_thl#3_7_1`:`epi_2_thl#3_7_13`,
            
            epi_2_thl24b_1:epi_2_thl24b_7,
            
            # UNIVERSAL
            epi_2_16a_1:epi_2_16a_7, epi_2_17a_1:epi_2_17a_7,
            epi_2_18b_1:epi_2_18b_7, epi_2_19a_1:epi_2_19a_7,
            epi_2_20b_1:epi_2_20b_7, epi_2_22d_1:epi_2_22d_7,
            epi_2_22e_1:epi_2_22e_7, epi_2_23d_1:epi_2_23d_7)) %>%
  mutate_at(vars(epi_2_02a_num, epi_2_03e_num, epi_2_04a_num, epi_2_05a_num,
                 epi_2_06d_num, epi_2_07a_num, epi_2_08b_num, epi_2_09b_num,
                 epi_2_10b_num, 
                 
                 # USA
                 epi_2_usa11b_num, epi_2_usa11c_1_num, epi_2_usa11c_2_num, 
                 epi_2_usa11c_3_num, epi_2_usa11c_4_num, epi_2_usa11c_5_num, 
                 epi_2_usa11c_6_num, epi_2_usa11c_7_num,
                 epi_2_usa12b_num, epi_2_usa12c_1_num, epi_2_usa12c_2_num,
                 epi_2_usa12c_3_num, epi_2_usa12c_4_num, epi_2_usa12c_5_num, 
                 epi_2_usa12c_6_num, epi_2_usa12c_7_num,
                 epi_2_usa13b_num, epi_2_usa13c_1_num, epi_2_usa13c_2_num,
                 epi_2_usa13c_3_num, epi_2_usa13c_4_num, epi_2_usa13c_5_num, 
                 epi_2_usa13c_6_num, epi_2_usa13c_7_num,
                 epi_2_usa14b_num, epi_2_usa14c_1_num, epi_2_usa14c_2_num,
                 epi_2_usa14c_3_num, epi_2_usa14c_4_num, epi_2_usa14c_5_num, 
                 epi_2_usa14c_6_num, epi_2_usa14c_7_num,
                 epi_2_usa15b_num, epi_2_usa15c_1_num, epi_2_usa15c_2_num,
                 epi_2_usa15c_3_num, epi_2_usa15c_4_num, epi_2_usa15c_5_num, 
                 epi_2_usa15c_6_num, epi_2_usa15c_7_num,
                 
                 # GHA
                 epi_2_gha11b_num, epi_2_gha11c_1_num, epi_2_gha11c_2_num, 
                 epi_2_gha11c_3_num, epi_2_gha11c_4_num, epi_2_gha11c_5_num, 
                 epi_2_gha11c_6_num, epi_2_gha11c_7_num,
                 epi_2_gha12b_num, epi_2_gha12c_1_num, epi_2_gha12c_2_num,
                 epi_2_gha12c_3_num, epi_2_gha12c_4_num, epi_2_gha12c_5_num, 
                 epi_2_gha12c_6_num, epi_2_gha12c_7_num,
                 epi_2_gha13b_num, epi_2_gha13c_1_num, epi_2_gha13c_2_num,
                 epi_2_gha13c_3_num, epi_2_gha13c_4_num, epi_2_gha13c_5_num, 
                 epi_2_gha13c_6_num, epi_2_gha13c_7_num,
                 epi_2_gha14b_num, epi_2_gha14c_1_num, epi_2_gha14c_2_num,
                 epi_2_gha14c_3_num, epi_2_gha14c_4_num, epi_2_gha14c_5_num, 
                 epi_2_gha14c_6_num, epi_2_gha14c_7_num,
                 epi_2_gha15b_num, epi_2_gha15c_1_num, epi_2_gha15c_2_num,
                 epi_2_gha15c_3_num, epi_2_gha15c_4_num, epi_2_gha15c_5_num, 
                 epi_2_gha15c_6_num, epi_2_gha15c_7_num,
                 
                 # CHN
                 epi_2_gha11b_num, epi_2_gha12b_num, epi_2_gha13b_num,
                 epi_2_gha14b_num, epi_2_gha15b_num,
                 
                 # THL
                 epi_2_thl12a_a_1_num, epi_2_thl12a_a_2_num, 
                 epi_2_thl12a_a_3_num, epi_2_thl12a_a_4_num, 
                 epi_2_thl12a_a_5_num, epi_2_thl12a_a_6_num, 
                 epi_2_thl12a_a_7_num,
                 
                 epi_2_thl12b_b_1_num, epi_2_thl12b_b_2_num, 
                 epi_2_thl12b_b_3_num, epi_2_thl12b_b_4_num, 
                 epi_2_thl12b_b_5_num, epi_2_thl12b_b_6_num, 
                 epi_2_thl12b_b_7_num,
                 
                 epi_2_thl12c_c_1_num, epi_2_thl12c_c_2_num, 
                 epi_2_thl12c_c_3_num, epi_2_thl12c_c_4_num, 
                 epi_2_thl12c_c_5_num, epi_2_thl12c_c_6_num, 
                 epi_2_thl12c_c_7_num,
                 
                 epi_2_thl12d_d_1_num, epi_2_thl12d_d_2_num, 
                 epi_2_thl12d_d_3_num, epi_2_thl12d_d_4_num, 
                 epi_2_thl12d_d_5_num, epi_2_thl12d_d_6_num, 
                 epi_2_thl12d_d_7_num,
                 
                 epi_2_thl12e_e_1_num, epi_2_thl12e_e_2_num, 
                 epi_2_thl12e_e_3_num, epi_2_thl12e_e_4_num, 
                 epi_2_thl12e_e_5_num, epi_2_thl12e_e_6_num, 
                 epi_2_thl12e_e_7_num,
                 
                 epi_2_thl12f_f_1_num, epi_2_thl12f_f_2_num, 
                 epi_2_thl12f_f_3_num, epi_2_thl12f_f_4_num, 
                 epi_2_thl12f_f_5_num, epi_2_thl12f_f_6_num, 
                 epi_2_thl12f_f_7_num,
                 
                 epi_2_thl12g_g_1_num, epi_2_thl12g_g_2_num, 
                 epi_2_thl12g_g_3_num, epi_2_thl12g_g_4_num, 
                 epi_2_thl12g_g_5_num, epi_2_thl12g_g_6_num, 
                 epi_2_thl12g_g_7_num,
                 
                 epi_2_thl12h_h_1_num, epi_2_thl12h_h_2_num, 
                 epi_2_thl12h_h_3_num, epi_2_thl12h_h_4_num, 
                 epi_2_thl12h_h_5_num, epi_2_thl12h_h_6_num, 
                 epi_2_thl12h_h_7_num,
                 
                 epi_2_thl12i_i_1_num, epi_2_thl12i_i_2_num, 
                 epi_2_thl12i_i_3_num, epi_2_thl12i_i_4_num, 
                 epi_2_thl12i_i_5_num, epi_2_thl12i_i_6_num, 
                 epi_2_thl12i_i_7_num,
                 
                 epi_2_thl12j_j_1_num, epi_2_thl12j_j_2_num, 
                 epi_2_thl12j_j_3_num, epi_2_thl12j_j_4_num, 
                 epi_2_thl12j_j_5_num, epi_2_thl12j_j_6_num, 
                 epi_2_thl12j_j_7_num,
                 
                 epi_2_thl12k_k_1_num, epi_2_thl12k_k_2_num, 
                 epi_2_thl12k_k_3_num, epi_2_thl12k_k_4_num, 
                 epi_2_thl12k_k_5_num, epi_2_thl12k_k_6_num, 
                 epi_2_thl12k_k_7_num,
                 
                 epi_2_thl14a_a_1_num, epi_2_thl14a_a_2_num, 
                 epi_2_thl14a_a_3_num, epi_2_thl14a_a_4_num, 
                 epi_2_thl14a_a_5_num, epi_2_thl14a_a_6_num, 
                 epi_2_thl14a_a_7_num,
                 
                 epi_2_thl14b_b_1_num, epi_2_thl14b_b_2_num, 
                 epi_2_thl14b_b_3_num, epi_2_thl14b_b_4_num, 
                 epi_2_thl14b_b_5_num, epi_2_thl14b_b_6_num, 
                 epi_2_thl14b_b_7_num,
                 
                 epi_2_thl14c_c_1_num, epi_2_thl14c_c_2_num, 
                 epi_2_thl14c_c_3_num, epi_2_thl14c_c_4_num, 
                 epi_2_thl14c_c_5_num, epi_2_thl14c_c_6_num, 
                 epi_2_thl14c_c_7_num,
                 
                 epi_2_thl14d_d_1_num, epi_2_thl14d_d_2_num, 
                 epi_2_thl14d_d_3_num, epi_2_thl14d_d_4_num, 
                 epi_2_thl14d_d_5_num, epi_2_thl14d_d_6_num, 
                 epi_2_thl14d_d_7_num,
                 
                 epi_2_thl14e_e_1_num, epi_2_thl14e_e_2_num, 
                 epi_2_thl14e_e_3_num, epi_2_thl14e_e_4_num, 
                 epi_2_thl14e_e_5_num, epi_2_thl14e_e_6_num, 
                 epi_2_thl14e_e_7_num,
                 
                 epi_2_thl24b_num,
                 
                 # UNIVERSAL
                 epi_2_16a_num, epi_2_17a_num, epi_2_18b_num, epi_2_19a_num,
                 epi_2_20b_num, epi_2_22d_num, epi_2_22e_num, epi_2_23d_num),
            funs(cat = recode_factor(.,
                                     "0" = "never",
                                     "1" = "once or twice",
                                     "2" = "at least once a year",
                                     "3" = "at least once a month",
                                     "4" = "at least once a week",
                                     "5" = "even more"))) %>%
  rename_at(vars(ends_with("_num_cat")),
            funs(gsub("_num_cat", "_cat", .))) %>%
  # response options: yes (1)
  mutate_at(vars(epi_2_10a_1:epi_2_10a_5, 
                 
                 # USA
                 epi_2_usa11a_1:epi_2_usa11a_8, epi_2_usa12a_1:epi_2_usa12a_8, 
                 epi_2_usa13a_1:epi_2_usa13a_8, epi_2_usa14a_1:epi_2_usa14a_8, 
                 epi_2_usa15a_1:epi_2_usa15a_8,
                 
                 # GHA
                 epi_2_gha11a_1:epi_2_gha11a_8, epi_2_gha12a_1:epi_2_gha12a_8, 
                 epi_2_gha13a_1:epi_2_gha13a_8, epi_2_gha14a_1:epi_2_gha14a_8, 
                 epi_2_gha15a_1:epi_2_gha15a_8,
                 
                 # CHN
                 epi_2_chn11a_1:epi_2_chn11a_8, epi_2_chn12a_1:epi_2_chn12a_8, 
                 epi_2_chn13a_1:epi_2_chn13a_8, epi_2_chn14a_1:epi_2_chn14a_8, 
                 epi_2_chn15a_1:epi_2_chn15a_8,
                 
                 # VUT
                 epi_2_vut11a_1:epi_2_vut11a_8, epi_2_vut12a_1:epi_2_vut12a_8, 
                 epi_2_vut13a_1:epi_2_vut13a_8, epi_2_vut14a_1:epi_2_vut14a_8, 
                 epi_2_vut15a_1:epi_2_vut15a_8,
                 
                 # THL
                 epi_2_thl14a, epi_2_thl14b, epi_2_thl14c, epi_2_thl14d,
                 epi_2_thl14e),
            funs(num = as.numeric(. %>% replace_na("0")),
                 cat = recode_factor(. %>% replace_na("0"),
                                     "0" = "no",
                                     "1" = "yes"))) %>%
  select(-c(epi_2_10a_1:epi_2_10a_5, 
            
            # USA
            epi_2_usa11a_1:epi_2_usa11a_8, epi_2_usa12a_1:epi_2_usa12a_8, 
            epi_2_usa13a_1:epi_2_usa13a_8, epi_2_usa14a_1:epi_2_usa14a_8, 
            epi_2_usa15a_1:epi_2_usa15a_8,
            
            # GHA
            epi_2_gha11a_1:epi_2_gha11a_8, epi_2_gha12a_1:epi_2_gha12a_8, 
            epi_2_gha13a_1:epi_2_gha13a_8, epi_2_gha14a_1:epi_2_gha14a_8, 
            epi_2_gha15a_1:epi_2_gha15a_8,
            
            # CHN
            epi_2_chn11a_1:epi_2_chn11a_8, epi_2_chn12a_1:epi_2_chn12a_8, 
            epi_2_chn13a_1:epi_2_chn13a_8, epi_2_chn14a_1:epi_2_chn14a_8, 
            epi_2_chn15a_1:epi_2_chn15a_8,
            
            # VUT
            epi_2_vut11a_1:epi_2_vut11a_8, epi_2_vut12a_1:epi_2_vut12a_8, 
            epi_2_vut13a_1:epi_2_vut13a_8, epi_2_vut14a_1:epi_2_vut14a_8, 
            epi_2_vut15a_1:epi_2_vut15a_8,
            
            # THL
            epi_2_thl14a, epi_2_thl14b, epi_2_thl14c, epi_2_thl14d,
            epi_2_thl14e))
# gather(question, response, -c(epi_batc, epi_ctry, epi_subj)) %>%
# arrange(epi_ctry, epi_subj, epi_batc, question) %>%
# mutate(qtype1 = case_when(grepl("a_", question) |
#                             grepl("b_", question) |
#                             grepl("c_", question) ~ "follow-up",
#                           TRUE ~ "base"),
#        qtype2 = case_when(grepl("_num", question) ~ "numeric",
#                           grepl("_cat", question) ~ "categorical"))
```

```{r}
d0_epi_demo <- d00 %>% 
  select(epi_batc:epi_subj, contains("_demo_")) %>%
  mutate(epi_demo_sex = factor(epi_demo_sex,
                               levels = c("Male", "Female", "Other")),
         epi_demo_age = gsub("~", "", epi_demo_age),
         epi_demo_age = gsub("Mid 40s", "45", epi_demo_age),
         epi_demo_age = as.numeric(epi_demo_age),
         epi_demo_edu = recode(
           epi_demo_edu,
           "Did not graduate HS" = "No HS degree",
           "High school" = "HS degree",
           "Vocational schooling (Politechnic school)" = "Vocational school",
           "Vocational schooling (Polytechnic school)" = "Vocational school",
           "Some college" = "Some college",
           "BA" = "Bachelors degree",
           "MA" = "Masters degree",
           "Graduate Degree (Ghana only)" = "Other graduate degree",
           "Non Specific Graduate Degree (only Ghana)" = "Other graduate degree",
           "PhD" = "Other graduate degree",
           "Other" = "Other"),
         epi_demo_edu = factor(epi_demo_edu,
                               levels = c("No HS degree", "HS degree",
                                          "Vocational school", "Some college",
                                          "Bachelors degree", "Masters degree",
                                          "Other graduate degree", "Other")),
         epi_demo_ubru = case_when(!is.na(epi_demo_ubru_1) ~ "Rural",
                                   !is.na(epi_demo_ubru_2) ~ "Urban"),
         epi_demo_ses_num = case_when(!is.na(epi_demo_ses_1) ~ -2,
                                      !is.na(epi_demo_ses_2) ~ -1,
                                      !is.na(epi_demo_ses_3) ~ 0,
                                      !is.na(epi_demo_ses_4) ~ 1,
                                      !is.na(epi_demo_ses_5) ~ 2),
         epi_demo_ses_cat = factor(epi_demo_ses_num,
                                   labels = c("much poorer", 
                                              "a little poorer", 
                                              "about the same", 
                                              "a little richer", 
                                              "much richer")),
         epi_demo_howr_cat = factor(tolower(epi_demo_howr),
                                    levels = c("strongly disagree", 
                                               "disagree", 
                                               "neither agree nor disagree", 
                                               "agree", 
                                               "strongly agree")),
         epi_demo_howr_num = as.numeric(epi_demo_howr_cat) - 3) %>%
  select(-c(epi_demo_ubru_1:epi_demo_ubru_3, epi_demo_ses_1:epi_demo_ses_6,
            epi_demo_howr)) %>%
  mutate_at(vars(epi_demo_affr, epi_demo_tung, epi_demo_ytng,
                 epi_demo_phn, epi_demo_email),
            funs(num = case_when(
              epi_demo_affr %in% c("1", "Yes", "yes", "Y", "y") ~ 1,
              epi_demo_affr %in% c("0", "No", "no", "N", "n") ~ 0))) %>%
  mutate_at(vars(epi_demo_affr_num, epi_demo_tung_num, epi_demo_ytng_num,
                 epi_demo_phn_num, epi_demo_email_num),
            funs(cat = factor(., levels = c("no", "yes")))) %>%
  rename_at(vars(ends_with("_num_cat")),
            funs(gsub("_num_cat", "_cat", .))) %>%
  select(-c(epi_demo_affr, epi_demo_tung, epi_demo_ytng,
            epi_demo_phn, epi_demo_email))
  # gather(question, response, -c(epi_batc, epi_ctry, epi_subj)) %>%
  # arrange(epi_ctry, epi_subj, epi_batc, question)
```

```{r}
d_demo <- d0_epi_demo %>%
  full_join(d0_epi_entry) %>%
  select(-c(epi_entr, epi_2day, epi_batc, epi_file, 
            contains("_phn_"), contains("_email_"))) %>%
  distinct()

write.csv(d_demo, "./data_wrangled/d_demo.csv")
```

# Porosity

```{r}
d_por <- d0_epi_1 %>% 
  select(epi_ctry, epi_subj, ends_with("_num")) %>%
  gather(question, response, -c(epi_ctry, epi_subj)) %>%
  mutate(question = gsub("_num", "", question)) %>%
  left_join(var_key) %>%
  mutate(epi_ctry = factor(epi_ctry, levels = c("US", "Ghana", "Thailand", 
                                                "China", "Vanuatu")))
```

```{r}
d_por_scored <- d_por %>%
  filter(!grepl("a", question), !grepl("b", question), 
         !grepl("c", question)) %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(# score_mean = mean(response, na.rm = T),
            score = sum(response, na.rm = T)) %>%
  ungroup() %>%
  mutate(epi_ctry = factor(epi_ctry, levels = c("US", "Ghana", "Thailand", 
                                                "China", "Vanuatu")))
```

```{r}
write.csv(d_por, "data_wrangled/d_por.csv")
write.csv(d_por_scored, "data_wrangled/d_por_scored.csv")
```


# Spiritual experiences

```{r}
d_spex <- d0_epi_2 %>% 
  select(epi_ctry, epi_subj, ends_with("_num")) %>%
  gather(question, response, -c(epi_ctry, epi_subj)) %>%
  mutate(question = gsub("_num", "", question)) %>%
  left_join(var_key) %>%
  mutate(epi_ctry = factor(epi_ctry, levels = c("US", "Ghana", "Thailand", 
                                                "China", "Vanuatu")))
```

```{r}
write.csv(d_spex, "data_wrangled/d_spex.csv")
```

```{r}
d_prayer <- d0_epi_2 %>%
  select(epi_ctry, epi_subj, ends_with("_num")) %>%
  gather(question, response, -c(epi_ctry, epi_subj)) %>%
  mutate(question = gsub("_num", "", question)) %>%
  filter(grepl("epi_2_01", question)) %>%
  left_join(var_key) %>%
  mutate(epi_ctry = factor(epi_ctry, levels = c("US", "Ghana", "Thailand", 
                                                "China", "Vanuatu")))
```

```{r}
write.csv(d_prayer, "data_wrangled/d_prayer.csv")
```

```{r}
d_spex_base_q2to23 <- d_spex %>%
  filter(question %in% c(
    # universal set 1
    "epi_2_02", "epi_2_03", "epi_2_04", "epi_2_05", "epi_2_06", "epi_2_07", 
    "epi_2_08", "epi_2_09", "epi_2_10", 
    # beings
    # USA
    "epi_2_usa11", "epi_2_usa12", "epi_2_usa13", "epi_2_usa14", "epi_2_usa15",
    # GHA
    "epi_2_gha11", "epi_2_gha12", "epi_2_gha13", "epi_2_gha14", "epi_2_gha15",
    # CHN
    "epi_2_chn11", "epi_2_chn12", "epi_2_chn13", "epi_2_chn14", "epi_2_chn15",
    # VUT
    "epi_2_vut11", "epi_2_vut12", "epi_2_vut13", "epi_2_vut14", "epi_2_vut15",
    # THL
    "epi_2_thl11", "epi_2_thl12a", "epi_2_thl12b", "epi_2_thl12c", 
    "epi_2_thl12d", "epi_2_thl12e", "epi_2_thl12f", "epi_2_thl12g", 
    "epi_2_thl12h", "epi_2_thl12i", "epi_2_thl12j", "epi_2_thl12k",
    # universal set 2
    "epi_2_16", "epi_2_17", "epi_2_18", "epi_2_19", "epi_2_20", "epi_2_21",
    # universal set 3
    "epi_2_22", "epi_2_23")) %>%
  # select(-order) %>%
  distinct()
```

```{r}
d_spex_base_q2to23_scored_propall <- d_spex_base_q2to23 %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score = mean(response, na.rm = T))

d_spex_base_q2to23_scored_first5 <- d_spex_base_q2to23 %>%
  filter(!question %in% c("epi_2_thl12e", "epi_2_thl12f", "epi_2_thl12g",
                          "epi_2_thl12h", "epi_2_thl12i", "epi_2_thl12j",
                          "epi_2_thl12k")) %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score = sum(response, na.rm = T))
```

```{r}
write.csv(d_spex_base_q2to23, "data_wrangled/d_spex_base_q2to23.csv")
write.csv(d_spex_base_q2to23_scored_propall, 
          "data_wrangled/d_spex_base_q2to23_scored_propall.csv")
write.csv(d_spex_base_q2to23_scored_first5, 
          "data_wrangled/d_spex_base_q2to23_scored_first5.csv")
```

```{r}
d_spex_base_q2to10 <- d_spex %>%
  filter(question %in% c("epi_2_02", "epi_2_03", "epi_2_04", "epi_2_05", 
                         "epi_2_06", "epi_2_07", "epi_2_08", "epi_2_09",
                         "epi_2_10")) %>%
  # select(-order) %>%
  distinct()
```

```{r}
d_spex_base_q2to10_scored <- d_spex_base_q2to10 %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score = sum(response, na.rm = T))
```

```{r}
write.csv(d_spex_base_q2to10, "data_wrangled/d_spex_base_q2to10.csv")
write.csv(d_spex_base_q2to10_scored, 
          "data_wrangled/d_spex_base_q2to10_scored.csv")
```

```{r}
d_spex_base_q11to15 <- d_spex %>%
  filter(question %in% c(
    # USA
    "epi_2_usa11", "epi_2_usa12", "epi_2_usa13", "epi_2_usa14", "epi_2_usa15",
    # GHA
    "epi_2_gha11", "epi_2_gha12", "epi_2_gha13", "epi_2_gha14", "epi_2_gha15",
    # CHN
    "epi_2_chn11", "epi_2_chn12", "epi_2_chn13", "epi_2_chn14", "epi_2_chn15",
    # VUT
    "epi_2_vut11", "epi_2_vut12", "epi_2_vut13", "epi_2_vut14", "epi_2_vut15",
    # THL
    "epi_2_thl11", "epi_2_thl12a", "epi_2_thl12b", "epi_2_thl12c", 
    "epi_2_thl12d", "epi_2_thl12e", "epi_2_thl12f", "epi_2_thl12g", 
    "epi_2_thl12h", "epi_2_thl12i", "epi_2_thl12j", "epi_2_thl12k")) %>%
  mutate(question_univ0 = case_when(
    question %in% c("epi_2_usa11", "epi_2_gha11", "epi_2_chn11", 
                    "epi_2_vut11", "epi_2_thl11") ~ "being01",
    question %in% c("epi_2_usa12", "epi_2_gha12", "epi_2_chn12", 
                    "epi_2_vut12", "epi_2_thl12a") ~ "being02",
    question %in% c("epi_2_usa13", "epi_2_gha13", "epi_2_chn13", 
                    "epi_2_vut13", "epi_2_thl12b") ~ "being03",
    question %in% c("epi_2_usa14", "epi_2_gha14", "epi_2_chn14", 
                    "epi_2_vut14", "epi_2_thl12c") ~ "being04",
    question %in% c("epi_2_usa15", "epi_2_gha15", "epi_2_chn15", 
                    "epi_2_vut15", "epi_2_thl12d") ~ "being05",
    question == "epi_2_thl12e" ~ "being06",
    question == "epi_2_thl12f" ~ "being07",
    question == "epi_2_thl12g" ~ "being08",
    question == "epi_2_thl12h" ~ "being09",
    question == "epi_2_thl12i" ~ "being10",
    question == "epi_2_thl12j" ~ "being11",
    question == "epi_2_thl12k" ~ "being12")) %>%
  mutate(question_univ1 = case_when(
    question %in% c("epi_2_usa11", "epi_2_gha11", "epi_2_chn11",
                    "epi_2_vut11") ~ "demon",
    question %in% c("epi_2_usa12", "epi_2_chn12") ~ "ghost",
    question %in% c("epi_2_usa13") ~ "dead",
    question %in% c("epi_2_usa14") ~ "nature spirit",
    question %in% c("epi_2_usa15", "epi_2_gha15", "epi_2_chn15") ~ "witch",
    question %in% c("epi_2_gha12", "epi_2_thl12j") ~ "angel",
    question %in% c("epi_2_gha13") ~ "ghost/ancestor",
    question %in% c("epi_2_gha14") ~ "abasom/maame water/dwarf",
    question %in% c("epi_2_chn13", "epi_2_thl12k") ~ "dead relative/ancestor",
    question %in% c("epi_2_chn14") ~ "animal spirit",
    question %in% c("epi_2_vut12") ~ "spirit of an ancestor/place",
    question %in% c("epi_2_vut13") ~ "spirit/ghost of a dead man/woman",
    question %in% c("epi_2_vut14") ~ "devil/dwarf",
    question %in% c("epi_2_vut15") ~ "witch/sorcerer/black magicker",
    question %in% c("epi_2_thl11") ~ "spirits in general",
    question %in% c("epi_2_thl12a") ~ "satan",
    question %in% c("epi_2_thl12b") ~ "devil",
    question %in% c("epi_2_thl12c") ~ "pii bpob (cannibalistic female spirit)",
    question %in% c("epi_2_thl12d") ~ "pii ga",
    question %in% c("epi_2_thl12e") ~ "place spirit",
    question %in% c("epi_2_thl12f") ~ "home spirit",
    question %in% c("epi_2_thl12g") ~ "pii dip",
    question %in% c("epi_2_thl12h") ~ "forest spirit",
    question %in% c("epi_2_thl12i") ~ "died spirit (had a bad death)"
  )) %>%
  mutate(question_univ2 = case_when(
    question %in% c("epi_2_usa11", "epi_2_gha11", "epi_2_chn11", "epi_2_vut11", 
                    "epi_2_vut14", "epi_2_thl12a", "epi_2_thl12b") 
    ~ "demon/devil/satan",
    question %in% c("epi_2_usa12", "epi_2_chn12", "epi_2_usa13", "epi_2_gha13",
                    "epi_2_chn13", "epi_2_thl12k", "epi_2_vut12", "epi_2_vut13",
                    "epi_2_thl12i") 
    ~ "ghost/dead/ancestor",
    question %in% c("epi_2_usa14", "epi_2_thl12e", "epi_2_thl12f", 
                    "epi_2_thl12h") 
    ~ "nature/place spirit",
    question %in% c("epi_2_usa15", "epi_2_gha15", "epi_2_chn15", "epi_2_vut15") 
    ~ "witch/sorcerer",
    question %in% c("epi_2_gha12", "epi_2_thl12j") ~ "angel",
    question %in% c("epi_2_gha14", "epi_2_chn14", "epi_2_thl11", 
                    "epi_2_thl12c", "epi_2_thl12d", "epi_2_thl12g") 
    ~ "other/general")) %>%
  # select(-order) %>%
  distinct()
```

```{r}
d_spex_base_q11to15_scored <- d_spex_base_q11to15 %>%
  filter(question_univ0 %in% 
           c("being01", "being02", "being03", "being04", "being05")) %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score_first5 = sum(response, na.rm = T)) %>%
  ungroup() %>% 
  full_join(d_spex_base_q11to15 %>%
              group_by(epi_ctry, epi_subj) %>%
              summarise(score_propall = mean(response, na.rm = T)) %>%
              ungroup()) %>%
  ungroup()
```

```{r}
write.csv(d_spex_base_q11to15, "data_wrangled/d_spex_base_q11to15.csv")
write.csv(d_spex_base_q11to15_scored,
          "data_wrangled/d_spex_base_q11to15_scored.csv")
```

```{r}
d_spex_base_q16to21 <- d_spex %>%
  filter(question %in% c("epi_2_16", "epi_2_17", "epi_2_18", "epi_2_19",
                         "epi_2_20", "epi_2_21")) %>%
  # select(-order) %>%
  distinct()
```

```{r}
d_spex_base_q16to21_scored <- d_spex_base_q16to21 %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score = sum(response, na.rm = T))
```

```{r}
write.csv(d_spex_base_q16to21, "data_wrangled/d_spex_base_q16to21.csv")
write.csv(d_spex_base_q16to21_scored, 
          "data_wrangled/d_spex_base_q16to21_scored.csv")
```

```{r}
d_spex_base_q22to23 <- d_spex %>%
  filter(question %in% c("epi_2_22", "epi_2_23")) %>%
  # select(-order) %>%
  distinct()
```

```{r}
d_spex_base_q22to23_scored <- d_spex_base_q22to23 %>%
  group_by(epi_ctry, epi_subj) %>%
  summarise(score = sum(response, na.rm = T))
```

```{r}
write.csv(d_spex_base_q22to23, "data_wrangled/d_spex_base_q22to23.csv")
write.csv(d_spex_base_q22to23_scored, 
          "data_wrangled/d_spex_base_q22to23_scored.csv")
```

